<?php
	global $Locale, $Translate;
?>

<div id="edusharing_rendering_metadata" role="contentinfo">
    <div class="edusharing_rendering_metadata_header">
        <img tabindex="0" class="edusharing_rendering_metadata_header_icon" src="<?php echo $previewUrl . (empty(Config::get('base64Preview')) ? (strpos($previewUrl, '?') !== FALSE ? '&' : '?') . 'crop=true&maxWidth=200&maxHeight=200' : '');?>">
        <h1 property="name" title="<?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?>" class="edusharing_rendering_metadata_header_title"><?php echo htmlentities($title) ?></h1>
    </div>
    <div class="edusharing_rendering_metadata_body">
        <?php echo $metadataHtml; ?>
    </div>
</div>