INSERT INTO `ESMODULE` (`ESMODULE_ID`, `ESMODULE_NAME`, `ESMODULE_DESC`) VALUES
(1, 'office', NULL),
(2, 'msoffice', NULL),
(3, 'doc', NULL),
(4, 'qti', NULL),
(5, 'qti21', 'QTI 2.1'),
(6, 'scorm', 'SCORM'),
(7, 'audio', NULL),
(8, 'video', NULL),
(9, 'picture', NULL),
(10, 'moodle', 'moodle 1.n'),
(11, 'scenario', 'scenario 1.n'),
(12, 'html', NULL),
(13, 'applet', 'applet 1.n'),
(14, 'url', 'URL'),
(15, 'learningapps', 'learningapps'),
(16, 'h5p', 'h5p'),
(17, 'lti', 'lti');
