CREATE TABLE IF NOT EXISTS `ESOBJECT_LOCK` (
  `ESOBJECT_CONVERSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ESOBJECT_LOCK_REP_ID` varchar(255) NOT NULL,
  `ESOBJECT_LOCK_OBJECT_ID` varchar(255) NOT NULL,
  `ESOBJECT_LOCK_OBJECT_VERSION` varchar(255) DEFAULT NULL,
  `ESOBJECT_LOCK_CONTENT_HASH` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ESOBJECT_CONVERSION_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
