CREATE TABLE `ESTRACK` (
  `ESTRACK_ID` int(11) NOT NULL auto_increment,
  `ESTRACK_ESOBJECT_ID` varchar(40) default NULL,
  `ESTRACK_TIME` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`ESTRACK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
