INSERT INTO `VERSION` (`VERSION_ID`, `VERSION_IDENT`, `VERSION_NAME`, `VERSION_DESC`, `VERSION_VNUMBER`, `VERSION_VBUILD`, `VERSION_PATCH`, `VERSION_TYPE`, `VERSION_AUTHOR`, `VERSION_URI`, `OWNER`, `WGROUP`, `ACCESS`, `COURSE_ID`, `DS_ID`, `VIEW`, `LAYOUT`, `RELSTATE`, `RELLANG`, `RELUSER`, `RELDATE`, `INSDAT`, `UPDDAT`, `UPDUSER`, `STATE`) VALUES
(1, 1, 'esrender', 'edu-sharing ', '3.1.0', 1, NULL, 'install', 'metaVentis GmbH', 'edu-sharing.net', 0, NULL, NULL, NULL, 0, NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, 'Y');

