<?php 
global $Locale, $Translate, $MC_URL;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
$msg['goToOriginConnector'] = new Phools_Message_Default('goToOriginConnector');
?>


<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/dynamic.php">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/metadata.css">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/url/url.css">

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
	<div class="edusharing_rendering_content_wrapper" >
		<?php if(empty($embedding)) {
			echo '<img class="edusharing_rendering_content_preview" src="'.$previewUrl.'" alt="'.$title.'">';
		} else {
            $iframeId = 'ltiframe_' . uniqid(); // Generate a unique ID for the iframe

            $script = <<<SCRIPT
            <script>
                const ltiIFrame = document.getElementById("$iframeId");
                if (ltiIFrame) {
                    console.log("ltiIFrame:$iframeId window.innerHeight:"+window.innerHeight + " top:" +ltiIFrame.getBoundingClientRect().top );
                    let h = window.innerHeight - ltiIFrame.getBoundingClientRect().top;
                    if(h < 300) h = window.innerHeight;
                    ltiIFrame.height = h + "px";
                } else console.log("no lti iframe found");
            </script>
            SCRIPT;

                $iframe = <<<HTML
            <div>
                <iframe 
                    id="$iframeId" 
                    allowfullscreen
                    src="$embedding&editMode=false&launchPresentation=iframe" 
                    style="border: none; max-width: 100%; width: 100%;">
                </iframe>
            </div>
            HTML;

            return $script . $iframe;
		}?>
        <?php
        //if(!$dataProtection) { ?>
		    <a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content edusharing_rendering_content-origin" id="edusharing_rendering_content_href"><?php
               if($ccressourcetype === 'connector') {
                   echo $msg['goToOriginConnector']->localize($Locale, $Translate);
               } else {
                   echo $msg['goToOrigin']->localize($Locale, $Translate);
               }
                ?></a>
        <?php
        //}
        ?>
	</div>
	<?php echo $metadata; ?>
</div>

<?php
if (!$dataProtection) {
    $downloadUrl = Config::get('downloadUrl');
    if(!empty($downloadUrl)) {
        echo '<script>setTimeout(function() {try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){console.log(err)}}, 1000);</script>';
    }
}
?>

