<?php
global $Locale, $Translate,  $MC_URL;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
$msg['goToOriginConnector'] = new Phools_Message_Default('goToOriginConnector');
?>

<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/embed.css">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/url/url.css">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/inline.php">

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <?php if(empty($embedding)) {
            echo '<img class="edusharing_rendering_content_preview" src="'.$previewUrl.'" alt="'.$title.'">';
        } else {
            echo $embedding;
        }?>
        <a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" data-nodeId="<?php echo $esObject-> getNode() -> ref -> id; ?>" id="edusharing_rendering_content_href"><?php
            if($ccressourcetype === 'connector') {
                echo $msg['goToOriginConnector']->localize($Locale, $Translate);
            } else {
                echo $msg['goToOrigin']->localize($Locale, $Translate);
            }
            ?></a>
    </div>
    <?php echo $footer?>
</div>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script src="<?php echo $MC_URL?>/vendor/js/tracking.js"></script>
