apiVersion: v2

name: ${helm.prefix}
description: ${helm.prefix}

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"

dependencies:

  - name: edu_sharing-community-common-lib
    repository: ${helm.deploy.url}
    version: 1.x.x

  - name: edu_sharing-community-common-postgresql
    repository: ${helm.deploy.url}
    version: 1.x.x
    alias: edusharing_services_rendering_postgresql
    condition: edusharing_services_rendering_postgresql.enabled

  - name: edu_sharing-community-common-rediscluster
    repository: ${helm.deploy.url}
    version: 1.x.x
    alias: edusharing_services_rendering_rediscluster
    condition: edusharing_services_rendering_rediscluster.enabled

  - name: ${helm.prefix}-service
    version: ${helm.chart.version}
    alias: edusharing_services_rendering_service
    condition: edusharing_services_rendering_service.enabled
