<?php 
global $Locale, $Translate;
$msg['contentReadPermissionDenied'] = new Phools_Message_Default('contentReadPermissionDenied');

?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    div.error {
        padding: 100px 10px;
        text-align: center;
    }
    div.message_wrapper {
        display: inline-block;
        background-color: #c6c6c6;
        color: #383838;
        padding: 5px;
        border-radius: 3px;
    }
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
       <img src="<?php echo $previewUrl?>">
        <div class="error">
            <div class="message_wrapper">
                <span class="message"><?php echo $msg['contentReadPermissionDenied']-> localize($Locale, $Translate);?></span>
            </div>
        </div>
	</div>
    <?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
</script>


