<?php 
global $Locale, $Translate;
?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
       <img src="https://kkytbsncd.org/wp-content/uploads/2017/02/66949567.jpg">
	</div>
    <?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
</script>


