<?php
global $Locale, $Translate;
$msg['error'] = new Phools_Message_Default('The object to which this collection object refers is no longer present.');
?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.css'); ?>
</style>
<img src="https://kkytbsncd.org/wp-content/uploads/2017/02/66949567.jpg">
<?php echo $metadata?>
