<?php
global $Locale, $Translate, $MC_URL;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<!-- js modified!!!!!!!! -->
<script type="text/javascript" src="<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-main.js"></script>

<script type="text/javascript">
    (function($) {
        $(function() {
            $('.h5p-container').h5p({
                frameJs: '<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-frame.min.js',
                frameCss: '<?php echo $MC_URL?>/theme/default/module/h5p/dist/styles/h5p.css',
                h5pContent: '<?php echo str_replace('cache/', '', $content)?>'
            });
        });
    })(H5P.jQuery);
</script>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
    <div class="edusharing_rendering_content_wrapper" role="main">
        <style scoped>
            /* http://meyerweb.com/eric/tools/css/reset/
   v2.0 | 20110126
   License: none (public domain)
*/

            html, body, div, span, applet, object, iframe,
            h1, h2, h3, h4, h5, h6, p, blockquote, pre,
            a, abbr, acronym, address, big, cite, code,
            del, dfn, em, img, ins, kbd, q, s, samp,
            small, strike, strong, sub, sup, tt, var,
            b, u, i, center,
            dl, dt, dd, ol, ul, li,
            fieldset, form, label, legend,
            table, caption, tbody, tfoot, thead, tr, th, td,
            article, aside, canvas, details, embed,
            figure, figcaption, footer, header, hgroup,
            menu, nav, output, ruby, section, summary,
            time, mark, audio, video {
                margin: 0;
                padding: 0;
                border: 0;
                font-size: 100%;
                font: inherit;
                vertical-align: baseline;
            }
            /* HTML5 display-role reset for older browsers */
            article, aside, details, figcaption, figure,
            footer, header, hgroup, menu, nav, section {
                display: block;
            }
            body {
                line-height: 1;
            }
            ol, ul {
                list-style: none;
            }
            blockquote, q {
                quotes: none;
            }
            blockquote:before, blockquote:after,
            q:before, q:after {
                content: '';
                content: none;
            }
            table {
                border-collapse: collapse;
                border-spacing: 0;
            }
            <?php include(dirname(__FILE__) . '/dist/styles/h5p.css');?>
        </style>
        <div class="edusharing_rendering_content h5p-container"></div>
    </div>
</div>

<?php echo $metadata; ?>


