<?php
global $Locale, $Translate, $MC_URL;
$uniqid = uniqid('h5p_');
$msg['h5p_ie_hint'] = new Phools_Message_Default('h5p_ie_hint');
?>

<link type="text/css" rel="stylesheet" media="all"
	href="<?php echo $MC_URL?>/theme/default/css/h5p.css" />

  <script type="text/javascript"
	src="<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-main.js"></script>


<script type="text/javascript">
    function waitForH5P(){
        if(typeof H5P !== "undefined"){
            (function($) {
                $('#<?php echo $uniqid?>').h5p({
                    frameJs: '<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-frame.min.js',
                    frameCss: '<?php echo $MC_URL?>/theme/default/css/h5p.css',
                    h5pContent: '<?php echo str_replace('cache/', '', $content)?>'
                });
            })(H5P.jQuery);}
        else{
            setTimeout(waitForH5P, 50);
        }
    }
    waitForH5P();
</script>
<div>
    <div id="<?php echo $uniqid?>" class="h5p-container"></div>
    <span class="edusharing_rendering_content_ie_hint"><?php echo $msg['h5p_ie_hint']->localize($Locale, $Translate) ?></span>
    <?php echo $footer?>
</div>

