<?php
$uniqid = uniqid('h5p_');
?>

<link type="text/css" rel="stylesheet" media="all"
	href="<?php echo $MC_URL?>/theme/default/css/h5p.css" />

  <script type="text/javascript"
	src="<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-main.js"></script>


<script type="text/javascript">
    function waitForH5P(){
        if(typeof H5P !== "undefined"){
            (function($) {
                $('#<?php echo $uniqid?>').h5p({
                    frameJs: '<?php echo $MC_URL?>/theme/default/module/h5p/dist/js/h5p-standalone-frame.js',
                    frameCss: '<?php echo $MC_URL?>/theme/default/css/h5p.css',
                    h5pContent: '<?php echo str_replace('cache/', '', $content)?>'
                });
            })(H5P.jQuery);}
        else{
            setTimeout(waitForH5P, 50);
        }
    }
    waitForH5P();
</script>

<div id="<?php echo $uniqid?>" class="h5p-container">H5P container</div>
<?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>')?>
<?php echo $metadata?>