<?php
$licid = $uniqueId . '_lic';
$id  = uniqid();
?>

<div>
    <?php if(empty($h5p_new)){ ?>
        <iframe id="<?php echo $h5pId?>" src="<?php echo $iframeurl?>" class="h5p-iframe h5p-initialized" data-licid="<?php echo $licid;?>" data-content-id="<?php echo $h5pId?>" style="width:85%;height:auto;border:none" allowfullscreen="allowfullscreen" frameBorder="0" scrolling="no"></iframe>
        <script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js" charset="UTF-8"></script>
    <?php }else{ ?>
        <h3><?php echo $h5p_new?></h3>
    <?php } ?>


    <!--<script>
        window.addEventListener('message', function(e) {
            var eventName = e.data[0];
            var data = e.data[1];
            switch(eventName) {
                case 'setHeight':
                    //height = data;
                    document.getElementById('<?php /*echo $id*/?>').style.height=data+'px';
                    //setRatio();
                    break;
            }
        }, false);    </script>-->
    <?php echo $footer?>
    <style>
        <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
        <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
    </style>
</div>
