<?php 
global $Locale, $Translate, $VIEWER_JS_CONFIG, $MC_URL;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<?php
if (!$allowPrintAndDownload) {
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdf.js"></script>';
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdfglobal.js"></script>';
}
?>

<style>
<?php include(dirname(__FILE__) . '/../../../css/dynamic.php'); ?>
<?php include(dirname(__FILE__) . '/../../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">


        <?php if (ENABLE_VIEWER_JS && isset($VIEWER_JS_CONFIG) && in_array('pdf', $VIEWER_JS_CONFIG)){
            if(Config::get('forcePreview')) {
                if(Config::get('showDownloadAdvice')) {
                    echo '<div id="edusharing_downloadadvice"><h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                        '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4></div>';
                }
                echo '<h1 class="edusharing_rendering_content_title">'.htmlentities($title).'</h1>' .
                    '<img class="edusharing_rendering_content_preview" src="' . $previewUrl . '" alt="">';
            } else {
                echo '
            <iframe id="docFrame" src="'.$MC_URL.'/vendor/js/pdfJS/index.php?file='.$content.'&pagemode=none" style="width:100%;height:100%;min-height:calc(100vh - 150px);border: none;">'.
                    '<h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                    '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4>' .
                    '</iframe>'.
                    '</div>';
            }
        } else {
            if(Config::get('forcePreview') || Config::get('isMobile')) {
                if(Config::get('showDownloadAdvice')) {
                    echo '<div id="edusharing_downloadadvice"><h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                        '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4></div>';
                }
                echo '<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>' .
                    '<img class="edusharing_rendering_content_preview" src="' . $previewUrl . '">';
            } else {
                echo '<div class="edusharing_rendering_content edusharing_rendering_content_embedded">' .
                    '<iframe src="' . $content . '#toolbar=0&pagemode=none" width="100%" height="100%" style="border: none;">' .
                    '<h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                    '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4>' .
                    '</iframe>'.
                    '</div>';
            }
        } ?>


    </div>
	<?php echo $metadata; ?>
</div>
