<?php
global $MC_URL, $Locale, $Translate;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<?php
if (!$allowPrintAndDownload) {
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdfglobal.js"></script>';
}
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/embed.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <iframe id="docFrame" src="<?php echo $MC_URL; ?>/vendor/js/pdfJS/web/index.php?file=<?php echo $content; ?>&pagemode=none">
            <h3><?php echo $msg['cannotOpenObject']->localize($Locale, $Translate); ?></h3>
            <h4><?php echo $msg['cannotOpenObjectText']->localize($Locale, $Translate); ?></h4>
        </iframe>
        <script src="<?php echo $MC_URL;?>/vendor/js/pdf.module.js"></script>
    </div>
</div>
