<?php
global $MC_URL, $Locale, $Translate;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<?php
if (!$allowPrintAndDownload) {
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdf.js"></script>';
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdfglobal.js"></script>';
}
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>

<div class="edusharing_rendering_content_wrapper" style="display: inline-block; width: 100%">
    <iframe id="docFrame" src="<?php echo $MC_URL; ?>/vendor/js/pdfJS/index.php?file=<?php echo $content; ?>" style="width:100%;height:100%;min-height:calc(100vh - 150px);border: none;">
        <h3><?php echo $msg['cannotOpenObject']->localize($Locale, $Translate); ?></h3>
        <h4><?php echo $msg['cannotOpenObjectText']->localize($Locale, $Translate); ?></h4>
    </iframe>

    <?php echo $footer?>
</div>
