<?php
global $MC_URL, $Locale, $Translate;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<?php
if (!$allowPrintAndDownload) {
    echo '<script src="'.$MC_URL.'/vendor/js/pdfJS/espdfglobal.js"></script>';
}
?>

<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/inline.php">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/metadata.css">

<div class="edusharing_rendering_content_wrapper" style="display: inline-block; width: 100%">
    <iframe id="docFrame" src="<?php echo $MC_URL; ?>/vendor/js/pdfJS/web/index.php?file=<?php echo $content; ?>&pagemode=none">
        <h3><?php echo $msg['cannotOpenObject']->localize($Locale, $Translate); ?></h3>
        <h4><?php echo $msg['cannotOpenObjectText']->localize($Locale, $Translate); ?></h4>
    </iframe>

    <?php echo $footer?>
</div>
