INSERT INTO "ESMODULE" ("ESMODULE_ID", "ESMODULE_NAME") VALUES
(1, 'office'),
(2, 'msoffice'),
(3, 'doc'),
(4, 'qti'),
(5, 'qti21'),
(6, 'scorm'),
(7, 'lti'),
(8, 'audio'),
(9, 'video'),
(10, 'picture'),
(11, 'moodle'),
(12, 'scenario'),
(13, 'html'),
(14, 'applet'),
(15, 'url'),
(16, 'learningapps'),
(17, 'h5p');
