CREATE TABLE "ESOBJECT_LOCK" (
  "ESOBJECT_CONVERSION_ID" SERIAL,
  "ESOBJECT_LOCK_REP_ID" varchar(255) default NULL,
  "ESOBJECT_LOCK_OBJECT_ID" varchar(255) default NULL,
  "ESOBJECT_LOCK_OBJECT_VERSION" varchar(255) default NULL,
  "ESOBJECT_LOCK_CONTENT_HASH" varchar(255) default NULL,
  PRIMARY KEY ("ESOBJECT_CONVERSION_ID")
);