CREATE TABLE "VERSION" (
  "VERSION_ID" SERIAL,
  "VERSION_VNUMBER" varchar(50) default NULL,
  "VERSION_REVISION" integer default NULL,
  "VERSION_TYPE" varchar(30) default NULL,
  "LASTCHANGE" timestamp NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  ("VERSION_ID")
);
