<?php

global $Locale, $Translate;
$msg = array();
$msg['seqenceChildren'] = new Phools_Message_Default('seqenceChildren :count', array(new Phools_Message_Param_String(':count', count($children))));
$msg['seqenceViewChildren'] = new Phools_Message_Default('seqenceViewChildren');
?>

<div class="edusharing_rendering_content_footer_sequence" >
<span onclick="var x = this.nextSibling; console.log(x); if (x.style.display === 'none') {x.style.display = 'block'; this.innerHTML='<i class=\'material-icons\'>keyboard_arrow_down</i><?php echo htmlentities($msg['seqenceChildren']->localize($Locale, $Translate))?>';} else {x.style.display = 'none';this.innerHTML='<i class=\'material-icons\'>keyboard_arrow_right</i><?php echo htmlentities($msg['seqenceChildren']->localize($Locale, $Translate))?>';}" class="edusharing_rendering_content_footer_sequence_toggle">
        <i class="material-icons">keyboard_arrow_right</i><?php echo htmlentities($msg['seqenceChildren']->localize($Locale, $Translate));?>
</span><ul style="display:none">
    <?php
foreach($children as $child) {
    echo '<li><a target="_blank" href="'.$parentUrl.'&childobject_order='.$child['{http://www.campuscontent.de/model/1.0}childobject_order'].'">
            <img style="width:20px; height: 20px" src="'.$child['iconUrl'].'">'.$child['{http://www.alfresco.org/model/content/1.0}name'].
         '</a></li>';
}
echo '<a class="edusharing_rendering_content_footer_sequence_showall" target="_blank" href="'.$parentUrl.'">'.htmlentities($msg['seqenceViewChildren']->localize($Locale, $Translate)).'<i class="material-icons">arrow_forward</i></a>';
echo '</ul>';
echo '</div>';


