<?php
global $MC_URL;
?>
<style>
    <?php include(dirname(__FILE__) . '/../../css/embed.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <div id="edusharing_rendering_content"></div>
    </div>
    <?php echo $footer?>
</div>
<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script>
    get_resource = function(authstring) {
        jQuery.ajax({
            url:"<?php echo $ajax_url ?>&callback=get_resource&"+authstring,
            success:function(data){
                jQuery("#edusharing_rendering_content").html(data);
            }
        });
    }
    get_resource("<?php echo $authString ?>");
</script>
