<?php
global $Locale, $Translate, $MC_URL;
$licid = uniqid();
?>
<style>
    <?php
        if ($css){
            include(dirname(__FILE__) . '/../../css/metadata.css');
            include(dirname(__FILE__) . '/../../css/inline.php');
        }
    ?>
</style>
<div class="edu_audio_wrapper">
    <video style="max-width:100%;box-shadow: none" id="" data-licid="<?php echo $licid;?>" src="<?php echo htmlentities($audio_url, ENT_QUOTES, 'UTF-8') ?>" type="audio/mp3" controls="controls" controlsList="nodownload" oncontextmenu="return false;"></video>
    <?php if (isset($footer)){
        echo $footer;
    }?>
</div>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
    const timeStamps = window.location.hash.substring(1);
    if (timeStamps !== "") {
        obj_<?php echo $licid;?>.src = obj_<?php echo $licid;?>.src + '#' + timeStamps;
    }
    if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
	    var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
	    for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
	    	if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
	        	wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
	    		wrapper_<?php echo $licid;?>.style.height = 'auto';
	          	break;
	        }
	    }
    }
</script>
