<?php 
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style>
<?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
<?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" >	
		<img class="edusharing_rendering_content_preview" src="<?php echo $previewUrl ?>">
		<a class="edusharing_rendering_content" href="javascript:var a=window.open('<?php echo htmlspecialchars($oru, ENT_QUOTES, 'UTF-8') ?>', 'ONYX', 'width=900,height=600,status=yes,scrollbars=yes,resizable=yes');a.focus();"><es:title xmlns:es="http://edu-sharing.net/object" ><?php echo $title; ?></es:title></a>
	</div>
	<?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>
