<?php
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" role="main">
        <img class="edusharing_rendering_content_preview" src="<?php echo $previewUrl ?>">
        <a class="edusharing_rendering_content" href="javascript:var a=window.open('<?php echo htmlspecialchars($oru, ENT_QUOTES, 'UTF-8') ?>', 'ONYX', 'width=900,height=600,status=yes,scrollbars=yes,resizable=yes');a.focus();"><es:title xmlns:es="http://edu-sharing.net/object" ><?php echo $title; ?></es:title></a>
    </div>
</div>
