<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.css'); ?>
</style>
<span>
<a href="javascript:var a=window.open('<?php echo htmlspecialchars($oru, ENT_QUOTES, 'UTF-8') ?>', 'edu-sharing ONYX', 'width=900,height=600,status=yes,scrollbars=yes,resizable=yes');a.focus();"><es:title xmlns:es="http://edu-sharing.net/object" ><?php echo $title; ?></es:title></a>
<?php if(!empty($metadata) || !empty($license)) {
    echo '&nbsp;(<span style="display: inline-block">'.$license.'</span>';
    if(!empty($metadata) && !empty($license))
        echo '&nbsp|&nbsp';
    echo '<span style="display: inline-block">'.$metadata.'</span>)';
}?>
</span>
