########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  annotations: {}

  cluster:

    istio:
      enabled: false

    pdb:
      enabled: false

    storage:
      data:
        permission: false
        spec: {}
      share:
        permission: false
        spec: {}

  image:
    pullPolicy: Always
    pullSecrets: []
    registry: ${docker.registry}
    repository: ${docker.repository}

  metrics:
    scrape:
      interval: 10s
      timeout: 10s
    servicemonitor:
      enabled: false

  patroni:
    enabled: false
    name: &nameOverride edusharing-postgresql
    postgres: "13"
    replicas: 3
    synchronous:
      enabled: true
      strict: true
    team: edusharing

  password: ""

  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: *nameOverride

images:
  postgres:
    db: ${docker.edu_sharing.community.common.postgresql}
    exporter: ${docker.edu_sharing.community.common.postgresql.exporter}
  minideb: ${docker.edu_sharing.community.common.minideb}

########################################################################################################################

service:

  port:
    api: 5432
    metrics: 9114

########################################################################################################################

config:

  database: postgresql
  username: postgresql
  password: ""

  extra:
    max_connections: "300"

  shmVolume:
    enabled: true
    sizeLimit: ""

########################################################################################################################

nodeAffinity: {}

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  share:
    data:
      create: true
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi

########################################################################################################################

podAnnotations: {}

podSecurityContext:

  fsGroup: 1001
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1001

########################################################################################################################

terminationGracePeriod: 120

startupProbe:

  failureThreshold: 30
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 4Gi

########################################################################################################################

init:

  permission:

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      runAsUser: 0

########################################################################################################################

job:

  dump:

    podAnnotations: {}

    resources:

      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

    schedule: "0 * * * *"

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001

########################################################################################################################

sidecar:

  metrics:

    enabled: true

    relabelings: []

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001

########################################################################################################################
