<style type='text/css'>
@import "../../theme/default/css/dynamic.css"
</style>

<div class="edusharing_rendering_wrapper">
	<div class="edusharing_rendering_metadata_top"><span class="edusharing_rendering_metadata_top_toggle edusharing_rendering_cursor_pointer" onClick="toggle_edusharing_rendering_metadata()">Informationen ein-/ausblenden</span></div>
		<?php echo $metadata?>
	<div class="edusharing_rendering_content_wrapper">
		<img class="edusharing_rendering_content" src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>">
	</div>
</div>

<script>
	function toggle_edusharing_rendering_metadata() {
		var el = document.getElementById('edusharing_rendering_metadata');
		el.style.display = (el.style.display != 'none' ? 'none' : '' );
	}
	
	function close_edusharing_rendering_metadata() {
		document.getElementById('edusharing_rendering_metadata').style.display = 'none';
		return true;
	}
</script>