<?php $licid = uniqid();?>
<link rel="stylesheet" href="<?php echo $MC_URL?>">
<div class="edusharing_rendering_content_wrapper" style="max-width: 100%; width:<?php echo htmlentities($width, ENT_QUOTES, 'UTF-8') ?>px;">
    <img style="max-width: 100%; width:<?php echo htmlentities($width, ENT_QUOTES, 'UTF-8') ?>px;" src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>" data-licid="<?php echo $licid;?>" alt="<?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?>" title="<?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?>" />
    <style>
        <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
        <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
    </style>
    <?php echo $footer?>
</div>