<?php $licid = uniqid();?>
<img style="max-width: 100%; width:<?php echo htmlentities($width, ENT_QUOTES, 'UTF-8') ?>px;" src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>" data-licid="<?php echo $licid;?>" alt="<?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?>" title="<?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?>" />
<?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>')?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<?php echo $metadata?>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    obj_<?php echo $licid;?>.onload = function() {
	    var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
	    if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
		    var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
		    for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
		    	if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
		        	wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
		    		wrapper_<?php echo $licid;?>.style.height = 'auto';
		    		obj_<?php echo $licid;?>.style.height = 'auto';
		          	break;
		        }
		    }
	    }
    }
</script>
