apiVersion: v2

name: ${helm.prefix}-services-rendering
description: ${helm.prefix}-services-rendering

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"
