########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  annotations: {}

  cluster:

    cert:
      annotations: {}

    ingress:
      ingressClassName: ""

    istio:
      enabled: false
      gateway:
        selector:
          app: istio-ingressgateway

    pdb:
      enabled: false

    storage:

      share:
        permission: false
        spec: {}

  image:
    pullPolicy: Always
    pullSecrets: []
    registry: ${docker.registry}
    repository: ${docker.repository}

  metrics:
    scrape:
      interval: 10s
      timeout: 10s
    servicemonitor:
      enabled: false

  patroni:
    enabled: false
    name: edusharing-rendering-postgresql
    secrets: "credentials.postgresql.acid.zalan.do"
    team: edusharing

  password: ""

  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-services-rendering-service

image:
  prefix: ${docker.prefix}
  tag: ${docker.tag}

########################################################################################################################

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPU: 80

########################################################################################################################

service:

  port:
    api:
      internal: 8080
      external: 8081
    metrics:
      api: 9117
      proxy: 9118

########################################################################################################################

ingress:

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

  hosts:
  - rendering.services.127.0.0.1.nip.io

  tls: []
#  - secretName: edusharing-services-rendering-tls
#    hosts:
#    - rendering.services.127.0.0.1.nip.io

  paths:
  - /esrender

########################################################################################################################

proxy:

  enabled: false
  config:
    backend:
      connectTimeout: 60
      firstByteTimeout: 180
      betweenBytesTimeout: 180
      maxConnections: 200
    cache:
      control: public
      ttl: 3600
    deliver:
      gzip: false

########################################################################################################################

config:

  cache:
    cluster: true
    database: 0
    host: edusharing-rediscluster
    port: 6379

  converter:
    audio:
      formats: "mp3"
    video:
      formats: "mp4,webm"
      resolution:
        all: "240,720,1080"
        default: "720"
      threads: 1
      timeout: 3600

  database:
    driver: pgsql
    host: edusharing-rendering-postgresql
    port: 5432
    database: rendering;sslmode=disabled
    username: rendering
    password: ""
    patroni: {}

  gdpr:
    enabled: false
    modules: []
#     - '"audio"'
#     - '"video"'
    urls: []
#     - regex: "/.*/"
#       name: "external Sources"
#       ref: "https://www.excample.com/gdpr"

  http:
    client:
      proxy:
        nonproxyhosts: []
        proxyhost: ""
        proxyport: ""
        proxyuser: ""
        proxypass: ""

  override:
    logging:
      application: ""

  plugins: []
#   - class: "ESRender_Plugin_...."
#     args: ['"arg1"','"arg2"']

  repository:
    host: edusharing-repository-service
    port: 8080
    password: ""

  viewer:
    enabled: true

  rendermoodle:
    url: ""
    token: ""
    categoryId: 1

########################################################################################################################

persistence:

  share:

    config:
      create: true
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
    data:
      create: true
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "soft"

tolerations: []

########################################################################################################################

podAnnotations: {}

podSecurityContext:

  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsUser: 1000

########################################################################################################################

terminationGracePeriod: 120

startupProbe:

  failureThreshold: 30
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

########################################################################################################################

init:

  permission:

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      runAsUser: 0

########################################################################################################################

job:

  init:

    podAnnotations: {}

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1000

  cachecleaner:

    podAnnotations: {}

    resources:

      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

    schedule: "0 * * * *"

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1000

########################################################################################################################

sidecar:

  metrics:

    enabled: true

    relabelings: []

    resources:
      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1000

  proxyCache:

    startupProbe:

      failureThreshold: 30
      initialDelaySeconds: 0
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10

    livenessProbe:

      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10

    readinessProbe:

      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

    resources:

      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 101

  proxyMetrics:

    relabelings: []

    resources:

      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 101

########################################################################################################################
