if (req.restarts > 0) {
set req.hash_always_miss = true;
}

if (req.url ~ "(\.css|\.eot|\.gif|\.ico|\.jpg|\.js|\.map|\.md|\.mjs|\.otf|\.png|\.scss|\.svg|\.svg|\.ts|\.ttf|\.txt|\.woff|\.woff2)") {
return (hash);
}
}

sub vcl_hit {
if (obj.ttl >= 0s) {
return (deliver);
}
return (restart);
}

sub vcl_backend_response {
      {{- if .Values.proxy.config.deliver.gzip }}
if (beresp.http.Content-Type ~ "^(text/|application/(xml|json|javascript))") {
set beresp.do_gzip = true;
}
if (beresp.http.Content-Type ~ "^(image/|audio/|video/|application/(pdf|zip))") {
set beresp.do_gzip = false;
}
      {{- end }}
if (bereq.url ~ "(\.css|\.eot|\.gif|\.ico|\.jpg|\.js|\.map|\.md|\.mjs|\.otf|\.png|\.scss|\.svg|\.svg|\.ts|\.ttf|\.txt|\.woff|\.woff2)") {
unset beresp.http.set-cookie;
set beresp.ttl = {{ .Values.proxy.config.cache.ttl }}s;
        {{- if .Values.proxy.config.cache.control }}
set beresp.http.cache-control = "{{ .Values.proxy.config.cache.control }}, max-age={{ .Values.proxy.config.cache.ttl }}";
        {{- end }}
return (deliver);
}
}

sub vcl_deliver {
unset resp.http.Via;
}
{{- end }}