apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_services_rendering.name" . }}-file
  labels: {{ include "edusharing_services_rendering.labels.app" . | nindent 4 }}
data:
{{- with .Values.config.override.logging.application }}
  logging-application: |
    {{ . | nindent 4 }}
{{- end }}