apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_services_rendering.name" . }}-env
  labels: {{ include "edusharing_services_rendering.labels.app" . | nindent 4 }}
data:
  CACHE_CLUSTER: {{ .Values.config.cache.cluster | quote }}
  CACHE_DATABASE: {{ .Values.config.cache.database | quote }}
  CACHE_HOST: {{ .Values.config.cache.host | quote }}
  CACHE_PORT: {{ .Values.config.cache.port | quote }}
  REPOSITORY_SERVICE_HOST: {{ .Values.config.repository.host | quote }}
  REPOSITORY_SERVICE_PORT: {{ .Values.config.repository.port | quote }}
  SERVICES_RENDERING_AUDIO_FORMATS: {{ .Values.config.converter.audio.formats | quote }}
  SERVICES_RENDERING_DATABASE_DRIV: {{ .Values.config.database.driver | quote }}
  SERVICES_RENDERING_DATABASE_HOST: {{ .Values.config.database.host | quote }}
  SERVICES_RENDERING_DATABASE_NAME: {{ .Values.config.database.database | quote }}
  SERVICES_RENDERING_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  SERVICES_RENDERING_SERVICE_GDPR_ENABLED: {{ .Values.config.gdpr.enabled | quote }}
  {{- with .Values.config.gdpr.modules }}
  SERVICES_RENDERING_SERVICE_GDPR_MODULES: '{{- join "," . }}'
  {{- end }}
  SERVICES_RENDERING_SERVICE_GDPR_URLS: |-
  {{- range $ununsed, $url := .Values.config.gdpr.urls }}
    {{ $url.regex | quote }} => ["name" => {{ $url.name | quote }}, "url" => {{ $url.ref | quote }}],
  {{- end }}
  SERVICES_RENDERING_SERVICE_HOST_EXTERNAL: {{ .Values.ingress.hosts | first | quote }}
  SERVICES_RENDERING_SERVICE_HOST_INTERNAL: {{ include "edusharing_services_rendering.name" . | quote }}
  SERVICES_RENDERING_SERVICE_PATH_EXTERNAL: {{ .Values.ingress.paths | first | quote }}
  SERVICES_RENDERING_SERVICE_PLUGINS: |-
  {{- range $ununsed, $plugin := .Values.config.plugins }}
    {{ $plugin.class }}([{{ range $k, $v := $plugin.args }}{{ $k | quote }} => {{ if kindIs "string" $v }}{{ $v | quote }}{{ else }}{{ $v }}{{ end }},{{ end }}]);
  {{- end }}
  SERVICES_RENDERING_SERVICE_PORT_EXTERNAL: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
  SERVICES_RENDERING_SERVICE_PORT_INTERNAL: {{ .Values.service.port.api.internal | quote }}
  SERVICES_RENDERING_SERVICE_PROT_EXTERNAL: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
  {{- with .Values.config.http.client.proxy.nonproxyhosts }}
  SERVICES_RENDERING_SERVICE_PROXY_NONPROXYHOSTS: '{{- join "," . }}'
  {{- end }}
  SERVICES_RENDERING_SERVICE_PROXY_HOST: {{ .Values.config.http.client.proxy.proxyhost | quote }}
  SERVICES_RENDERING_SERVICE_PROXY_PORT: {{ .Values.config.http.client.proxy.proxyport | quote }}
  SERVICES_RENDERING_SERVICE_PROXY_USER: {{ .Values.config.http.client.proxy.proxyuser | quote }}
  SERVICES_RENDERING_SERVICE_PROXY_PASS: {{ .Values.config.http.client.proxy.proxypass | quote }}
  SERVICES_RENDERING_SERVICE_VIEWER_ENABLED: {{ .Values.config.viewer.enabled | quote }}
  SERVICES_RENDERING_RENDERMOODLE_URL: {{ .Values.config.rendermoodle.url | quote }}
  SERVICES_RENDERING_RENDERMOODLE_TOKEN: {{ .Values.config.rendermoodle.token | quote }}
  SERVICES_RENDERING_RENDERMOODLE_CATEGORY_ID: {{ .Values.config.rendermoodle.categoryId | quote }}
  SERVICES_RENDERING_VIDEO_FORMATS: {{ .Values.config.converter.video.formats | quote }}
  SERVICES_RENDERING_VIDEO_RESOLUTIONS: {{ .Values.config.converter.video.resolution.all | quote }}
  SERVICES_RENDERING_VIDEO_DEFAULT_RESOLUTION: {{ .Values.config.converter.video.resolution.default | quote }}
