apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-cachecleaner
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: cachecleaner
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.job.cachecleaner.schedule | quote }}
  suspend: {{ .Values.job.cachecleaner.suspend }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
            {{- with merge .Values.job.cachecleaner.podAnnotations .Values.global.annotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ include "edusharing_common_lib.names.name" . }}-job-cachecleaner
            image: {{ include "edusharing_common_lib.images.image" . }}{{ .Values.job.cachecleaner.image.name }}:{{ .Values.job.cachecleaner.image.tag }}
            imagePullPolicy: {{ .Values.global.image.pullPolicy }}
            args: ["php", "func/classes.new/Helper/cacheCleaner.php"]
            {{- $patroni := merge .Values.config.database.patroni .Values.global.patroni }}
            {{- if $patroni.enabled }}
            env:
              - name: SERVICES_RENDERING_DATABASE_PASS
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.config.database.username }}.{{ $patroni.name }}.{{ $patroni.secrets }}
                    key: password
            {{- end }}
            envFrom:
            - configMapRef:
                name: {{ include "edusharing_common_lib.names.name" . }}-env
            - secretRef:
                name: {{ include "edusharing_common_lib.names.name" . }}-env
            volumeMounts:
            - name: share-config
              mountPath: /var/cache/esrender/config
            - name: share-data
              mountPath: /var/cache/esrender/data
            {{- with .Values.job.cachecleaner.startupProbe }}
            startupProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo startupProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              successThreshold: {{ .successThreshold }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.cachecleaner.livenessProbe }}
            livenessProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo livenessProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.cachecleaner.readinessProbe }}
            readinessProbe:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "echo readinessProbe > /dev/null"
              failureThreshold: {{ .failureThreshold }}
              initialDelaySeconds: {{ .initialDelaySeconds }}
              periodSeconds: {{ .periodSeconds }}
              successThreshold: {{ .successThreshold }}
              timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- with .Values.job.cachecleaner.resources }}
            resources: {{ toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.job.cachecleaner.securityContext }}
            securityContext: {{ toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.global.image.pullSecrets }}
          imagePullSecrets: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with merge .Values.podSecurityContext .Values.global.security }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.terminationGracePeriod }}
          terminationGracePeriodSeconds: {{ . }}
          {{- end }}
          {{- with .Values.nodeAffinity }}
          affinity:
            nodeAffinity: {{ toYaml . | nindent 14 }}
          {{- end }}
          volumes:
          - name: share-config
            persistentVolumeClaim:
              claimName: {{ include "edusharing_services_rendering.pvc.share.config" . }}
          - name: share-data
            persistentVolumeClaim:
              claimName: {{ include "edusharing_services_rendering.pvc.share.data" . }}
