{{- if .Values.global.cluster.istio.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "edusharing_services_rendering.name" . }}
  labels: {{ include "edusharing_services_rendering.labels.app" . | nindent 4 }}
spec:
  selector: {{ toYaml .Values.global.cluster.istio.gateway.selector | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: {{ toYaml .Values.ingress.hosts | nindent 6 }}
  {{- range .Values.ingress.tls }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .secretName }}
    hosts: {{ toYaml .hosts | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}