<?php
global $Locale, $Translate;
$licid = uniqid();
?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.css'); ?>
</style>
<span>
<a href="<?php echo htmlspecialchars($url, ENT_COMPAT, 'utf-8') ?>" target="_blank"><?php echo htmlspecialchars($title, ENT_COMPAT, 'utf-8') ?></a>
    <?php if(!empty($metadata) || !empty($license)) {
        echo '&nbsp;(<span style="display: inline-block">'.$license.'</span>';
        if(!empty($metadata) && !empty($license))
            echo '&nbsp|&nbsp';
        echo '<span style="display: inline-block">'.$metadata.'</span>)';
    }?>
</span>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    obj_<?php echo $licid;?>.onload = function() {
        var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
        if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
            var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
            for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
                if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
                    wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
                    wrapper_<?php echo $licid;?>.style.height = 'auto';
                    obj_<?php echo $licid;?>.style.height = 'auto';
                    break;
                }
            }
        }
    }
</script>
