<?php
global $Locale, $Translate;
$licid = uniqid();
?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<div>
    <a href="<?php echo htmlspecialchars($url, ENT_COMPAT, 'utf-8') ?>" target="_blank"><?php echo htmlspecialchars($title, ENT_COMPAT, 'utf-8') ?></a>
    <?php echo $footer?>
</div>