apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}-env
  labels: {{ include "edusharing_rediscluster.labels.app" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_ALLOW_REMOTE_CONNECTIONS: "yes"
  REDIS_AOF_ENABLED: "{{ if .Values.config.aof.enabled }}yes{{ else }}no{{ end }}"
  REDIS_CLUSTER_DYNAMIC_IPS: "yes"
  REDIS_CLUSTER_REPLICAS: {{ .Values.config.cluster.replicas | quote }}
  REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP: {{ .Values.config.cluster.wait | quote }}
  REDIS_NODES: '{{ range $i := until (include "edusharing_rediscluster.replicas" . | int) }}{{ include "edusharing_rediscluster.name" $ }}-{{ $i }}.{{ include "edusharing_rediscluster.name" $ }}-headless {{ end }}'
