{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}
  labels: {{ include "edusharing_rediscluster.labels.app" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.config.cluster.replicas }}
  selector:
    matchLabels: {{ include "edusharing_rediscluster.labels.app" . | nindent 6 }}
{{- end }}