<style>
    <?php include(dirname(__FILE__) . '/../../css/embed.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
            <?php echo '<div class="edusharing_rendering_content edusharing_rendering_content_embedded">' .
                '<iframe title="' . $title . '" src="' . $content . '" width="100%" height="100%" style="border: none;">' .
                '</iframe>'.
                '</div>';
        ?>
    </div>
    <?php echo $footer?>
</div>
