<?php 
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
<?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
        <?php echo $dataProtectionRegulationsDialog ?>
		<iframe id="<?php echo $uniqueId?>" src="<?php echo $url?>" width="100%" height="500px" style="border: none; display:none;" ></iframe>
	</div>
	<?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>