<?php
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
    <div class="edusharing_rendering_content_wrapper" role="main">
        <iframe id="<?php echo $uniqueId?>" src="<?php echo $url?>" width="100%" height="500px" style="border: none;" ></iframe>
    </div>
</div>
