<?php
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>
<style>
    <?php include(dirname(__FILE__) . '/../../css/embed.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
    <div class="edusharing_rendering_content_wrapper" role="main">
        <iframe id="<?php echo $uniqueId?>" src="<?php echo $url?>" width="95%" height="100%" style="border: none; height: 80vh" ></iframe>
    </div>
</div>
