<?php 
global $Locale, $Translate;
$licid = uniqid();
$msg['showInLearningAppsOrg'] = new Phools_Message_Default('showInLearningAppsOrg');
?>
<div>
    <style scoped>
        <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
        <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
    </style>
    <iframe src="<?php echo $url?>" data-licid="<?php echo $licid;?>" width="100%" height="500px" style="border: none;"></iframe>
    <br/><a href="<?php echo $originUrl?>" target="_blank" title="<?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?>"><?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?></a>
    <?php echo $footer?>
</div>