<?php 
global $Locale, $Translate;
$licid = $uniqueId . '_lic';
$msg['showInLearningAppsOrg'] = new Phools_Message_Default('showInLearningAppsOrg');
?>
<?php echo $dataProtectionRegulationsDialog ?>
<iframe id="<?php echo $uniqueId?>" data-src="<?php echo $url?>" src="" data-licid="<?php echo $licid;?>" width="100%" height="500px" style="border: none; display: none;"></iframe>
<br/><a href="<?php echo $originUrl?>" target="_blank" title="<?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?>"><?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?></a>
<?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>')?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<?php echo $metadata?>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    obj_<?php echo $licid;?>.onload = function() {
        var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
        if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
            var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
            for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
                if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
                    wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
                    wrapper_<?php echo $licid;?>.style.height = 'auto';
                    obj_<?php echo $licid;?>.style.height = 'auto';
                    break;
                }
            }
        }
    }
</script>
