<?php
global $Locale, $Translate;
$msg = array();
?>

<style>
    <?php include(dirname(__FILE__) . '/../../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
    <div class="edusharing_rendering_content_wrapper" role="main">
        <iframe class="edusharing_etherpad" src="<?php echo $url?>"></iframe>
    </div>
    <?php echo $metadata; ?>
</div>
