<?php
global $Locale, $Translate;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['hasNoContentLicense'] = new Phools_Message_Default('hasNoContentLicense');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
$msg['goToLogin'] = new Phools_Message_Default('goToLogin');

?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <?php
        if(Config::get('hasContentLicense') === false) {
            echo '<h3>' . $msg['hasNoContentLicense']->localize($Locale, $Translate) . '</h3>';
            if($loginAvailable) {
                echo '<h3><a href="/edu-sharing/components/login?next=' .
                    urlencode("components/render/{$node->ref->id}")
                    . '">' . $msg['goToLogin']->localize($Locale, $Translate) .'</a></h3>';
            }
        } else if(Config::get('showDownloadAdvice'))
            echo '<div id="edusharing_downloadadvice"><h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4></div>';
        ?>
        <h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
        <img class="edusharing_rendering_content_preview" src="<?php echo $previewUrl?>" alt="<?php echo htmlentities($title,ENT_QUOTES,'UTF-8') ?>">

        <?php if(!empty(Config::get('omega'))){
            echo '<a href="' .  Config::get('omega') . '" class="edusharing_rendering_content" target="_blank" id="edusharing_rendering_content_href">' .  $msg['goToOrigin']->localize($Locale, $Translate) . '</a>';
        }
        ?>

        <?php
        if($node->aspects && in_array('ccm:collection', $node->aspects)) {
            $url = explode("render", $node->content->url);
            echo '<a href="' .  $url[0] . 'collections?id=' . $node->ref->id .'" class="edusharing_rendering_content" id="edusharing_rendering_content_href">' .  $msg['goToOrigin']->localize($Locale, $Translate) . '</a>';
        } else if(Config::get('showDownloadButton') && Config::get('hasContentLicense') === true){
            echo '<a href="' .  $url . '" download="'.$title.'" class="edusharing_rendering_content" id="edusharing_rendering_content_href">' .  $msg['toDownload']->localize($Locale, $Translate) . '</a>';
        }
        ?>
    </div>
    <?php echo $metadata; ?>
</div>

<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>
