<?php
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
$msg['showDocument'] = new Phools_Message_Default('showDocument');
?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
    <div class="edusharing_rendering_content_wrapper" role="main">
            <img class="edusharing_rendering_content_preview" src="<?php echo $previewUrl?>">
        <a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" id="edusharing_rendering_content_href"><?php echo $msg['showDocument']->localize($Locale, $Translate);?></a>
    </div>
    <?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>