<?php
    global $Locale, $Translate, $MC_DOCROOT, $MC_PATH;
    $msg = array();
    $msg['back'] = new Phools_Message_Default('back');
    if(!empty($backLink))
        $backCloseHref = $backLink;
    else 
        $backCloseHref = 'javascript:window.close();';

?>
<!DOCTYPE html>
<html>
    <head>
        <title>edu-sharing audio module</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <link rel="stylesheet" type="text/css" href="../../theme/default/css/display.css">
        <link rel="stylesheet" type="text/css" href="../../theme/default/css/custom.css">
        <link rel="stylesheet" type="text/css" href="../../theme/default/css/progressbar.css">
        <script type="text/javascript" src="../../vendor/js/getJS.php?<?php echo filemtime($MC_DOCROOT . $MC_PATH . '/vendor/js/getJS.php') ?>"></script>
        <script>
            get_resource = function() {
                jQuery.ajax({
                    url:"<?php echo $ajax_url ?>&callback=get_resource&token="+token,
                    success:function(result){
                        jQuery("#content").html(result);
                        document.getElementsByTagName('audio')[0].play();
                    }
                });
            }
            get_resource("<?php echo $token ?>");
        </script>
    </head>
    <body oncontextmenu="return false;">
        <nav>
            <a class="action back" href="<?php echo $backCloseHref; ?>"><?php echo $msg['back']->localize($Locale, $Translate);?></a>
        </nav>
        <section>
            <div id="content"></div>
        </section>
    </body>
</html>
