<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
</style>

<div class="edusharing_rendering_wrapper">
	<div class="edusharing_rendering_metadata_top"><span id="edusharing_rendering_metadata_top_toggle" class="edusharing_rendering_cursor_pointer" onClick="toggle_edusharing_rendering_metadata()"><?php echo $msg['hideInformation']->localize($Locale, $Translate);?></span></div>
		<?php echo $metadata?>
	<div class="edusharing_rendering_content_wrapper">
		<div id="edusharing_rendering_content"></div>
	</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script>
	get_resource = function(authstring) {
	    jQuery.ajax({
	        url:"<?php echo $ajax_url ?>&callback=get_resource&"+authstring,
	        success:function(data){
	            jQuery("#edusharing_rendering_content").html(data);
	        }
	    });
	}
	
	get_resource("<?php echo $authString ?>");
	
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
	
</script>