<?php
global $MC_URL;
?>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" role="main">
        <div id="edusharing_rendering_content"></div>
    </div>
    <?php echo $metadata; ?>
</div>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>

<script>
    get_resource = function(authstring) {
        jQuery.ajax({
            url:"<?php echo $ajax_url ?>&callback=get_resource&"+authstring,
            success:function(data){
                jQuery("#edusharing_rendering_content").html(data);
            }
        });
    }

    get_resource("<?php echo $authString ?>");

</script>