<?php $licid = uniqid();?>
<audiostyle="max-width:100%" id="" data-licid="<?php echo $licid;?>" src="<?php echo htmlentities($audio_url, ENT_QUOTES, 'UTF-8') ?>" type="audio/mp3" controls="controls"></audio>
<?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>')?>
<?php echo $metadata?>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
    if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
	    var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
	    for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
	    	if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
	        	wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
	    		wrapper_<?php echo $licid;?>.style.height = 'auto';
	          	break;
	        }
	    }
    }
</script>