<?php
global $MC_URL;
$uniqueId = rand();
?>
    <script id="eduGetJS" src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
    <script src="<?php echo $MC_URL?>/theme/default/data_protection/script.js"></script>
    <style>
        <?php include(dirname(__FILE__) . '/../css/dynamic.php'); ?>
        <?php include(dirname(__FILE__) . '/../css/metadata.css'); ?>
    </style>
    <div class="edusharing_rendering_wrapper" id="<?php echo $uniqueId;?>-privacy">
        <h1 class="edusharing_rendering_content_title"><?php echo $node->getNode()->title ?></h1>
        <div class="edusharing_rendering_content_wrapper" role="main">
            <div class="dataProtectionRegulations">
                <img class="dataProtectionVideoBg" src="<?php echo $node->getNode()->preview->url ?>"></img>
                <div class="dataProtectionRegulationsContainer">
                    <?php
                    if($type === RemoteObjectType::$TYPE_GENERIC) {
                        ?>

                        <div class="dataProtectionExternalLink">
                        <span class="dataProtectionRegulationsHeading"><?php
                            echo Phools_Message_Default::translate('dataProtectionExternalHeading');
                            ?>
                        </span>
                            <p><?php
                                echo Phools_Message_Default::translate('dataProtectionExternalDescription');
                                ?>
                                <a href="<?php echo $handler['url'];?>" target="_blank">
                                    <?php echo Phools_Message_Default::translate('dataProtectionRegulations');?>
                                </a>
                            </p>
                            <p>
                                <a href="<?php echo $url; ?>" class="edusharing_rendering_content btn btn-primary dataProtectionRegulationsButton dataProtectionRegulationsButton-<?php echo $type;?>" target="_blank" id="edusharing_rendering_content_href">
                                    <?php echo Phools_Message_Default::translate('goToOrigin'); ?>
                                </a>
                            </p>

                        </div>
                        <?php
                    } else {
                        ?>
                        <span class="dataProtectionRegulationsHeading"><?php
                            echo Phools_Message_Default::translate('dataProtectionRegulations1 :providerName', [':providerName' => $handler['name']])
                            ?>
                </span>
                        <p><?php
                            echo Phools_Message_Default::translate('dataProtectionRegulations2 :providerName', [':providerName' => $handler['name']]);
                            ?></p>
                        <p>
                            <b><?php echo Phools_Message_Default::translate('dataProtectionRegulations3');?></b><br/>
                            <a href="<?php echo $handler['url'];?>" target="_blank"><?php echo Phools_Message_Default::translate('dataProtectionRegulations');?></a>
                            <br/>
                            <a href="#"
                               id="<?php echo $uniqueId; ?>-btn"
                               data-id="<?php echo $uniqueId; ?>"
                               data-content="<?php echo htmlspecialchars($content); ?>"
                               class="edusharing_rendering_content btn btn-primary dataProtectionRegulationsButton dataProtectionRegulationsButton-<?php echo $type;?>"
                            ><?php echo Phools_Message_Default::translate('dataProtectionRegulations4');?></a>
                        </p>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div id="<?php echo $uniqueId;?>-data"></div>

<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<input type="hidden" id="esRenderDownloadUrl" value="'.$downloadUrl.'">';
?>