<div class="edusharing_rendering_content_footer">
    <div class="edusharing_rendering_content_footer_top">
           <?php echo $metadata ?>
        <?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>'); ?>
    </div>
    <div class="edusharing_rendering_content_footer_bot">
        <?php echo $sequence;?>
    </div>
</div>
