<?php 
global $Locale, $Translate;
$msg = array();
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<style>
<?php include(dirname(__FILE__) . '/../../../css/dynamic.css'); ?>
<?php include(dirname(__FILE__) . '/../../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">


        <?php if(Config::get('forcePreview')) {
            if(Config::get('showDownloadAdvice')) {
                echo '<div id="edusharing_downloadadvice"><h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                    '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4></div>';
            }
            echo '<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>' .
                    '<img class="edusharing_rendering_content_preview" src="' . $previewUrl . '">';
        } else {
            echo '<div class="edusharing_rendering_content edusharing_rendering_content_embedded">' .
                '<iframe src="' . $content . '" width="100%" height="100%" style="border: none;">' .
                '<h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4>' .
                '</iframe>'.
            '</div>';
        }
        ?>
    </div>
	<?php echo $metadata; ?>
</div>