<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['toDownload'] = new Phools_Message_Default('toDownload');
$msg['cannotOpenObject'] = new Phools_Message_Default('cannotOpenObject');
$msg['cannotOpenObjectText'] = new Phools_Message_Default('cannotOpenObjectText');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../../css/dynamic.css'); ?>
<?php include(dirname(__FILE__) . '/../../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
        <div class="edusharing_rendering_content edusharing_rendering_content_embedded">
            <iframe src="<?php echo $content?>" width="100%" height="100%" style="border: none;">
                <?php
                    echo '<h3>' . $msg['cannotOpenObject']->localize($Locale, $Translate) . '</h3>' .
                        '<h4>' . $msg['cannotOpenObjectText']->localize($Locale, $Translate) . '</h4>';
                    if(Config::get('showDownloadButton'))
                        echo '<a href="' . $url .'" target="_blank" class="edusharing_rendering_content" >' . $msg['toDownload']->localize($Locale, $Translate) . '</a>';
                ?>
            </iframe>
        </div>
    </div>
	<?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../../js/dynamic.js'); ?>
</script>