<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../../css/dynamic.css'); ?>
<?php include(dirname(__FILE__) . '/../../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
        <div class="edusharing_rendering_content edusharing_rendering_content_embedded">
            <object data="<?php echo $content?>" type="application/pdf" width="100%" height="100%">
                <iframe src="<?php echo $content?>" width="100%" height="100%" style="border: none;">
                    This browser does not support PDFs. Please download the PDF to view it: <a href="<?php echo $content?>">Download PDF</a>
                </iframe>
            </object>
        </div>
    </div>
	<?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../../js/dynamic.js'); ?>
</script>