<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" role="main">
            <?php echo '<div class="edusharing_rendering_content edusharing_rendering_content_embedded">' .
                '<iframe src="' . $content . '" width="100%" height="100%" style="border: none;">' .
                '</iframe>'.
                '</div>';
        ?>
    </div>
</div>