<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">	
		<?php echo '<img class="edusharing_rendering_content_preview" src="'.$previewUrl.'">'?>
		<a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" ><?php echo $msg['goToOrigin']->localize($Locale, $Translate);?></a>
	</div>
	<?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
</script>