<?php
global $Locale, $Translate;
$msg = array();
$msg['hasNoContentLicense'] = new Phools_Message_Default('hasNoContentLicense');
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<div>
    <?php
    if(false === Config::get('hasContentLicense')) {
        echo '<span class="edusharing_warning">'.htmlentities($msg['hasNoContentLicense']->localize($Locale, $Translate), ENT_COMPAT, 'utf-8').'</span>';
    } else {
        echo '<a href="'. htmlentities($url, ENT_COMPAT, 'utf-8').'" target="_blank"  ><es:title xmlns:es="http://edu-sharing.net/object" >'.$title.'</es:title></a>';
    }
    echo $footer;
    ?>

</div>
