{{- if not .Values.global.patroni.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-env
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
data:
  POSTGRESQL_DATABASE: {{ .Values.config.database | quote }}
{{- end }}