{{- if .Values.global.cluster.istio.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  host: {{ include "edusharing_postgresql.name" . }}
{{- end }}
{{- end }}
