{{- if not .Values.global.patroni.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-env
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
type: Opaque
data:
  POSTGRESQL_PASSWORD: {{ default .Values.global.password .Values.config.password | b64enc | quote }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ default .Values.global.password .Values.config.password | b64enc | quote }}
  POSTGRESQL_USERNAME: {{ .Values.config.username | b64enc | quote }}
{{- end }}