<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
            get_resource = function() {
                jQuery.ajax({
                    url:"<?php echo $ajax_url ?>&callback=get_resource",
                    success:function(data){
                        jQuery("#edusharing_rendering_content").html(data);
                    }
                });
            }
            get_resource();
        </script>
<div id="edusharing_rendering_content"></div>
<span id="edusharing_rendering_metadata_toggle">TOGGLE</span>
<div id="edusharing_rendering_metadata">
<h1>Titel des Objekts</h1>
<label>Eigentümer</label>
<span>Name des Eigentümers</span>
<label>Quelle</label>
<span>Name der Quelle</span>
<label>Lizenz</label>
<span>Bild und Text der Lizenz</span>
<label>Weitere Metadaten</label>
<span>kommen hier</span>
</div>