<?php
/*
 *
 * View used if object locked or while conversion
 * 
 * calls js function specified in $callback
 * 
 */

define('TIMEOUT_INTERVAL', 5000);
 
global $Locale, $Translate, $ROOT_URI;

echo '<span data-view="lock"></span>';
if($progress == 0 && $positionInConversionQueue) {
    $msg1 = new Phools_Message_Default('Resource is waiting for conversion.');
    $msg2 = new Phools_Message_Default('Postition in queue');
    echo '<p class="renderservice_message">' . $msg1 -> localize($Locale, $Translate) . '<br/>';
    echo $msg2 -> localize($Locale, $Translate) . ':&nbsp;' . $positionInConversionQueue . '</p>';
} else {
    $msg1 = new Phools_Message_Default('Resource is being converted for your view ...');
    echo '<p class="renderservice_message">' . htmlentities($msg1 -> localize($Locale, $Translate), ENT_QUOTES, 'UTF-8'). ' '.$progress.'%</p>';
    echo '<div style="height: 20px; max-width: 300px;border: 1px solid #ddd;" class="es_progressbar_container"><span class="es_progressbar_progress" style="display: inline-block; height: 100%; width:'.$progress.'%; background-color: #ddd;"></span></div>';
}

if(!empty($callback))
    echo "<script>var t = setTimeout('{$callback}(\"".$authString."\")', ".TIMEOUT_INTERVAL.");</script>";