<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<?php
		if(!empty($metadata)) {		
			echo '<div class="edusharing_rendering_metadata_top"><span id="edusharing_rendering_metadata_top_toggle" title="' . $msg['hideInformation']->localize($Locale, $Translate) . '" class="edusharing_rendering_cursor_pointer" tabindex="0" onkeypress="(event.keyCode==13)?toggle_edusharing_rendering_metadata():0" onClick="toggle_edusharing_rendering_metadata()">' . $msg['hideInformation']->localize($Locale, $Translate) . '</span></div>';
			echo $metadata;
		}
	?>
	<div class="edusharing_rendering_content_wrapper" role="main">	
		<?php if(empty($embedding)) {
			echo '<img class="edusharing_rendering_content_preview" src="'.$previewUrl.'">';
		} else {
			echo $embedding;
		}?>
		<a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" ><?php echo $msg['goToOrigin']->localize($Locale, $Translate);?></a>
	</div>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
</script>