<style>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<div>
<a href="javascript:var a=window.open('<?php echo htmlspecialchars($oru, ENT_QUOTES, 'UTF-8') ?>', 'edu-sharing ONYX', 'width=900,height=600,status=yes,scrollbars=yes,resizable=yes');a.focus();"><es:title xmlns:es="http://edu-sharing.net/object" ><?php echo $title; ?></es:title></a>
<?php echo $footer?>
</div>
