<?php
	global $Locale, $Translate;
	
	require_once __DIR__ . '/../../../func/classes.new/Helper/MetadataRendererHelper.php';
	
	$msg['meta_general'] = new Phools_Message_Default('meta_general');
	$msg['meta_contributors'] = new Phools_Message_Default('meta_contributors');
	$msg['meta_contributors_content'] = new Phools_Message_Default('meta_contributors_content');
	$msg['meta_contributors_metadata'] = new Phools_Message_Default('meta_contributors_metadata');
	$msg['meta_didactics'] = new Phools_Message_Default('meta_didactics');
?>

<div id="edusharing_rendering_metadata" role="contentinfo">
		<div class="edusharing_rendering_metadata_header">
			<img tabindex="0" class="edusharing_rendering_metadata_header_icon" onclick="showContent()" onkeypress="(event.keyCode==13)?showContent():0" src="<?php echo $meta['{http://www.alfresco.org/model/rendition/1.0}rendition']['value'] ?>">
			<h1 property="name" title="<?php echo $title ?>" class="edusharing_rendering_metadata_header_title"><?php echo $title ?></h1>
		</div>
		<div class="edusharing_rendering_metadata_body">
			<div class="edusharing_rendering_metadata_body_left">	
			
			<?php 
				/*
				 * GENERAL INFORMATION
				 */
				$metadataGeneral = '<h2>'.$msg['meta_general']->localize($Locale, $Translate).'</h2>';
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.alfresco.org/model/content/1.0}title']);			
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/lom/1.0}general_keyword'], '', array('rschip'));

				if(!empty($meta['{http://www.campuscontent.de/model/1.0}commonlicense_key']['value'])) {
					$metadataGeneral .= '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}commonlicense_key'])) . '</label>';
					$metadataGeneral .= '<a class="edusharing_rendering_metadata_body_value" href="'.$meta['{virtualproperty}licenseurl']['value'].'" target="_blank" style="margin-left:15px"><img src="'.$meta['{virtualproperty}licenseicon']['value'].'"></a>';
				}
				
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherVCARD_EXT_LOM_CONTRIBUTE_DATE'], 'date');
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/lom/1.0}general_description']);
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.alfresco.org/model/content/1.0}createdISO8601'], 'date');
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.alfresco.org/model/content/1.0}modifiedISO8601'], 'date');
				$metadataGeneral .= MetadataRendererHelper::render($meta['{http://www.alfresco.org/model/system/1.0}node-uuid']);
				
				echo $metadataGeneral;
	
				
				/*
				 * CONTRIBUTORS
				 */
				$metadataContributors = '<h2>'.$msg['meta_contributors']->localize($Locale, $Translate).'</h2>';
				$metadataContributors .= '<h3>'.$msg['meta_contributors_content']->localize($Locale, $Translate).'</h3>';
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_initiatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_terminatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_validatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_editorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_graphical_designerFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_technical_implementerFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_content_providerFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_educational_validatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_script_writerFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_instructional_designerFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_subject_matter_expertFN'],'', array('rschip', 'people'));
				$metadataContributors .= '<h3>'.$msg['meta_contributors_metadata']->localize($Locale, $Translate).'</h3>';
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_creatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_validatorFN'],'', array('rschip', 'people'));
				$metadataContributors .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_providerFN'],'', array('rschip', 'people'));
				
				echo $metadataContributors;
				
			?>
			</div>
			<div class="edusharing_rendering_metadata_body_right">
			
			
			<?php 
				
				/*
				 * DIDACTICS
				 */
				$metadataDidactics = '<h2>' . $msg['meta_didactics']->localize($Locale, $Translate) . '</h2>';
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}taxonentry']);
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}educationallearningresourcetype'], '', array('rschip'));
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}educationalcontext'], '', array('rschip'));
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}educationalintendedenduserrole'], '', array('rschip', 'group'));
			
				if(!empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['value']) || !empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_to']['value'])) {
					$metadataDidactics .= '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['label'])) . '</label>';
					$metadataDidactics .=  '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['value']) . '</span>';
					if(!empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['value']) && !empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_to']['value']))
						$metadataDidactics .=  '&nbsp;&ndash;&nbsp;';
					$metadataDidactics .=  '<span class="edusharing_rendering_metadata_body_value" style="margin-left: 0">' . htmlentities($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_to']['value']) . '</span>';
				}

				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/lom/1.0}general_language']);
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/lom/1.0}aggregationlevel']);
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.edu-sharing.net/model/lisum/1.0}systematics_path']);
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.campuscontent.de/model/1.0}classification_keyword'], '', array('rschip'));
				$metadataDidactics .= MetadataRendererHelper::render($meta['{http://www.edu-sharing.net/model/lisum/1.0}keyword_geo'], '', array('rschip'));
				
				echo $metadataDidactics;
	
				?>
			
			</div>
		</div>
		<div tabindex="0" id="edusharing_scrolltotop" onClick="showContent()" onkeypress="(event.keyCode==13)?showContent():0"></div>
	</div>