<?php
	global $Locale, $Translate;
	
	$msg['meta_general'] = new Phools_Message_Default('meta_general');
	$msg['meta_contributors'] = new Phools_Message_Default('meta_contributors');
	$msg['meta_didactics'] = new Phools_Message_Default('meta_didactics');
?>

<div id="edusharing_rendering_metadata" role="contentinfo">
		<div class="edusharing_rendering_metadata_header">
			<img tabindex="0" class="edusharing_rendering_metadata_header_icon" onclick="showContent()" onkeypress="(event.keyCode==13)?showContent():0" src="<?php echo $meta['{http://www.alfresco.org/model/rendition/1.0}rendition']['value'] ?>">
			<h1 property="name" title="<?php echo $title ?>" class="edusharing_rendering_metadata_header_title"><?php echo $title ?></h1>
		</div>
		<div class="edusharing_rendering_metadata_body">
			<div class="edusharing_rendering_metadata_body_left">
			
			<h2><?php echo $msg['meta_general']->localize($Locale, $Translate);?></h2>
			<?php
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.alfresco.org/model/content/1.0}title']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.alfresco.org/model/content/1.0}title']['value']) . '</span>';
			
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/lom/1.0}general_keyword']['label'])) . '</label>';
				$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/lom/1.0}general_keyword']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip">' . htmlentities($value) . '</span>';
				}
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}commonlicense_key']['label'])) . '</label>';
				echo '<a class="edusharing_rendering_metadata_body_value" href="'.$meta['{virtualproperty}licenseurl']['value'].'" target="_blank" style="margin-left:15px"><img src="'.$meta['{virtualproperty}licenseicon']['value'].'"></a>';				
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherVCARD_EXT_LOM_CONTRIBUTE_DATE']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities(date('d. F Y', strtotime($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherVCARD_EXT_LOM_CONTRIBUTE_DATE']['value']))) . '</span>';
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/lom/1.0}general_description']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.campuscontent.de/model/lom/1.0}general_description']['value']) . '</span>';
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.alfresco.org/model/content/1.0}createdISO8601']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities(date('d. F Y, H:i', strtotime($meta['{http://www.alfresco.org/model/content/1.0}createdISO8601']['value']))) . '</span>';
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.alfresco.org/model/content/1.0}modifiedISO8601']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities(date('d. F Y, H:i', strtotime($meta['{http://www.alfresco.org/model/content/1.0}modifiedISO8601']['value']))) . '</span>';
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.alfresco.org/model/system/1.0}node-uuid']['label'])) . '</label>';
				echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.alfresco.org/model/system/1.0}node-uuid']['value']) . '</span>';

			?>
			
			
			<h2><?php echo $msg['meta_contributors']->localize($Locale, $Translate);?></h2>
			<?php 
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_authorFN']['label'])) . '</label>';
				if(!empty($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_authorFN']['value']))
					echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_authorFN']['value']) . '</span>';

				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_publisherFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_unknownFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_unknownFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_initiatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_initiatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_terminatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_terminatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_validatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_validatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_editorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_editorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_graphical_designerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_graphical_designerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_technical_implementerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_technical_implementerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_content_providerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_content_providerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_educational_validatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_educational_validatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_script_writerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_script_writerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_instructional_designerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_instructional_designerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_subject_matter_expertFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}lifecyclecontributer_subject_matter_expertFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_creatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_creatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_validatorFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_validatorFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				
				echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_providerFN']['label'])) . '</label>';
				$valArray = explode('[#]',$meta['{http://www.campuscontent.de/model/1.0}metadatacontributer_providerFN']['value']);
				foreach($valArray as $value) {
					if(!empty($value))
						echo '<span class="edusharing_rendering_metadata_body_value rschip people">' . htmlentities($value) . '</span>';
				}
				

				?>
			</div>
			<div class="edusharing_rendering_metadata_body_right">
			
			
				<h2><?php echo $msg['meta_didactics']->localize($Locale, $Translate);?></h2>
			
			<?php 
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}taxonentry']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/1.0}taxonentry']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value block">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}educationallearningresourcetype']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/1.0}educationallearningresourcetype']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value rschip">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}educationalcontext']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/1.0}educationalcontext']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value rschip">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}educationalintendedenduserrole']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/1.0}educationalintendedenduserrole']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value rschip group">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['label'])) . '</label>';
			echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['value']) . '</span>';
			if(!empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_from']['value']) && !empty($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_to']['value']))
				echo '&nbsp;&ndash;&nbsp;';
			echo '<span class="edusharing_rendering_metadata_body_value" style="margin-left: 0">' . htmlentities($meta['{http://www.campuscontent.de/model/1.0}educationaltypicalagerange_to']['value']) . '</span>';
				
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/lom/1.0}general_language']['label'])) . '</label>';
			echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.campuscontent.de/model/lom/1.0}general_language']['value']) . '</span>';
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/lom/1.0}aggregationlevel']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/lom/1.0}aggregationlevel']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.edu-sharing.net/model/lisum/1.0}systematics_path']['label'])) . '</label>';
			echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($meta['{http://www.edu-sharing.net/model/lisum/1.0}systematics_path']['value']) . '</span>';
			
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.campuscontent.de/model/1.0}classification_keyword']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.campuscontent.de/model/1.0}classification_keyword']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($value) . '</span>';
			}
			
			echo '<label class="edusharing_rendering_metadata_body_label">' . htmlentities(ucfirst($meta['{http://www.edu-sharing.net/model/lisum/1.0}keyword_geo']['label'])) . '</label>';
			$valArray = explode('[#]', $meta['{http://www.edu-sharing.net/model/lisum/1.0}keyword_geo']['value']);
			foreach($valArray as $value) {
				if(!empty($value))
					echo '<span class="edusharing_rendering_metadata_body_value">' . htmlentities($value) . '</span>';
			}
			
			?>
			
			</div>
		</div>
		<div tabindex="0" id="edusharing_scrolltotop" onClick="showContent()" onkeypress="(event.keyCode==13)?showContent():0"></div>
	</div>