<?php
	global $Locale, $Translate;
	$msg['title'] = new Phools_Message_Default('title');
	$msg['showMetadata'] = new Phools_Message_Default('showMetadata');
	$msg['hideMetadata'] = new Phools_Message_Default('hideMetadata');
?>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div class="edusharing_metadata_wrapper">
	<a class="edusharing_metadata_toggle_button" data-textopen="<?php echo $msg['showMetadata']->localize($Locale, $Translate);?>" data-textclose="<?php echo $msg['hideMetadata']->localize($Locale, $Translate);?>"><?php echo $msg['showMetadata']->localize($Locale, $Translate);?></a>
	<div class="edusharing_metadata" style="display:none">
		<?php echo $metadataHtml ?>
	</div>
</div>
