<?php
global $MC_URL;
session_start();
$id = uniqid();
$_SESSION["mod_audio"][$id]=[
    "ajax_url" => $ajax_url,
    "authString" => $authString
];
?>
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/embed.css">
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <div id="edusharing_rendering_content"></div>
    </div>
    <?php echo $footer?>
</div>
<script src="<?php echo $MC_URL?>/vendor/js/audio.module.php?ID=<?php echo urlencode($id);?>&PHPSESSID=<?php echo urlencode(session_id());?>"></script>
