<?php
global $Locale, $Translate, $MC_URL;
$licid = uniqid();

if ($css) {
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/inline.php">';
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/metadata.css">';
}
?>
<div class="edu_audio_wrapper">
    <video poster="<?php echo $preview_resource_url;?>" id="" data-licid="<?php echo $licid;?>" src="<?php echo htmlentities($audio_url, ENT_QUOTES, 'UTF-8') ?>" type="audio/mp3" controls="controls" controlsList="nodownload"></video>
    <?php if (isset($footer)){
        echo $footer;
    }?>
</div>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
    const timeStamps_<?php echo $licid;?> = window.location.hash.substring(1);
    if (timeStamps_<?php echo $licid;?> !== "") {
        obj_<?php echo $licid;?>.src = obj_<?php echo $licid;?>.src + '#' + timeStamps_<?php echo $licid;?>;
    }
    if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
        var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
        for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
            if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
                wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
                wrapper_<?php echo $licid;?>.style.height = 'auto';
                break;
            }
        }
    }
</script>
