<?php
global $Locale, $Translate, $MC_URL;
$licid = uniqid();

if ($css) {
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/inline.php">';
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/metadata.css">';
}
?>
<div class="edu_audio_wrapper">
    <data class="edu_audio_data" value='<?php echo json_encode(["preview" => $preview_resource_url, "resource" => $audio_url]);?>'></data>
    <?php if (isset($footer)){
        echo $footer;
    }?>
</div>
