<?php
/*
 *
 * View used if object locked or while conversion
 * 
 * calls js function specified in $callback
 * 
 */

global $Locale, $Translate, $ROOT_URI, $MC_URL;

echo '<script src="' . $MC_URL . '/vendor/js/audio/lock.js" type="text/javascript" charset="utf-8"></script>';
echo '<link rel="stylesheet" href="' . $MC_URL .'/vendor/css/audio/lock.css">';

echo '<span data-view="lock"></span>';
if($progress == 0 && $positionInConversionQueue) {
    $msg1 = new Phools_Message_Default('Resource is waiting for conversion.');
    $msg2 = new Phools_Message_Default('Postition in queue');
    echo '<p class="renderservice_message">' . $msg1 -> localize($Locale, $Translate) . '<br/>';
    echo $msg2 -> localize($Locale, $Translate) . ':&nbsp;' . $positionInConversionQueue . '</p>';
} else {
    $msg1 = new Phools_Message_Default('Resource is being converted for your view ...');
    echo '<p class="renderservice_message">' . htmlentities($msg1 -> localize($Locale, $Translate), ENT_QUOTES, 'UTF-8'). ' '.$progress.'%</p>';
    echo '<div class="es_progressbar_container"><span id="es_progressbar_progress" class="es_progressbar_progress" data-progress="' . $progress . '"></span></div>';
}
if(!empty($callback)) {
    $jsonData = json_encode(['callback' => $callback, 'authString' => $authString]);
    echo '<data value=' . $jsonData .'></data>';
}