<?php
global $Locale, $Translate;
$msg = array();
$msg['imageDescriptionNotAvailable'] = new Phools_Message_Default('imageDescriptionNotAvailable');
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
    <div class="edusharing_rendering_content_wrapper" >
        <div class="edusharing_rendering_fullscreen_wrapper">
            <img
                    class="edusharing_rendering_content"
                    src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>"
                    alt="<?php echo $msg['imageDescriptionNotAvailable'] -> localize($Locale, $Translate) ?>"
            >
            <i id="edusharing_toggle_fullscreen" class="material-icons">fullscreen</i>
        </div>
    </div>
    <?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script src="<?php echo $MC_URL?>/theme/default/js/fullscreen.js"></script>