<?php
global $Locale, $Translate;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
$msg['showDocument'] = new Phools_Message_Default('showDocument');
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
    <div class="edusharing_rendering_content_wrapper">
<!--            <img class="edusharing_rendering_content_preview" src="--><?php //echo $previewUrl?><!--">-->
        <iframe src="<?php echo $url ?>" width="90%" height="800" frameBorder="0" style="display: block; margin: 0 auto;"></iframe>
        <a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" id="edusharing_rendering_content_href"><?php echo $msg['showDocument']->localize($Locale, $Translate);?></a>
    </div>
    <?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>
