<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../../css/dynamic.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">	
		<object id="htmlobject" data="<?php echo $path?>" style="display: block; min-height: 400px; width: 100%; background: #fff"></object>
	</div>
	<?php echo $metadata; ?>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../../js/dynamic.js'); ?>
</script>