<?php 
global $Locale, $Translate, $MC_URL;
$msg = array();
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
	<div class="edusharing_rendering_content_wrapper">
		<div id="edusharing_rendering_content"
			data-ajax-url="<?php echo htmlspecialchars($ajax_url, ENT_QUOTES, 'UTF-8') ?>"
			data-auth-string="<?php echo htmlspecialchars($authString, ENT_QUOTES, 'UTF-8') ?>"></div>
	</div>
	<?php echo $metadata; ?>
</div>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script src="<?php echo $MC_URL?>/vendor/js/video/dynamic.js"></script>
