<?php
global $Locale, $Translate, $MC_URL;
$msg = array();
session_start();
$id = uniqid();
$_SESSION["mod_video"][$id] = [
    "ajax_url"   => $ajax_url,
    "authString" => $authString
];
?>

<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/dynamic.php">
<link rel="stylesheet" href="<?php echo $MC_URL;?>/vendor/css/metadata.css">

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
	<div class="edusharing_rendering_content_wrapper">
		<div id="edusharing_rendering_content_<?php echo $id; ?>"></div>
	</div>
	<?php echo $metadata; ?>
</div>

<script src="<?php echo $MC_URL?>/vendor/js/video.module.php?ID=<?php echo urlencode($id);?>&PHPSESSID=<?php echo urlencode(session_id());?>"></script>