<?php
global $Locale, $Translate, $MC_URL;
require_once (__DIR__ . '/../../../../conf/audio-video.conf.php');

$errMsg = new Phools_Message_Default('Video player cannot play back this video.');
$conversionMsg = new Phools_Message_Default('inConversionQueue');
$settingsLabel = new Phools_Message_Default('Set video resolution');
$licid = uniqid();
$styleVideo = '';
if(isset($_REQUEST['width']) && !empty($_REQUEST['width'])){
    $styleVideo = 'width:'.(int)$_REQUEST['width'] . 'px';
}

$defaultRes = VIDEO_DEFAULT_RESOLUTION;
$videoResolutions = VIDEO_RESOLUTIONS;
if ( empty($url[$defaultRes]) ){
    $defaultRes = $videoResolutions[0];
}

if ($css) {
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/metadata.css">';
    echo '<link rel="stylesheet" href="' . $MC_URL . '/vendor/css/inline.php">';
}
?>
<div class="edusharing_rendering_content_video_wrapper">
    <video src="<?php echo $url[$defaultRes]?>"<?php if($styleVideo !== ''){ echo ' style="'.$styleVideo.'"'; } ?> data-tap-disabled="true" id="<?php echo $videoObjectIdentifier?>" data-licid="<?php echo $licid;?>" controls controlsList="nodownload"></video>
    <div id="edusharing_rendering_content_video_options_container_<?php echo $videoObjectIdentifier ?>" class="edusharing_rendering_content_video_options_container">
        <button id="edusharing_rendering_content_video_options_button<?php echo $videoObjectIdentifier ?>" class="edusharing_rendering_content_video_options" aria-label="<?php echo $settingsLabel->localize($Locale, $Translate) ?>" aria-haspopup="true">
            <i class="material-icons edusharing_rendering_content_video_options_toggle">settings</i>
        </button>
        <div class="edusharing_rendering_content_video_options_content">
            <ul role="menu" id="edusharing_rendering_content_video_options_resolutions_<?php echo $videoObjectIdentifier ?>" class="edusharing_rendering_content_video_options_resolutions" aria-labelledby="edusharing_rendering_content_video_options_button<?php echo $videoObjectIdentifier ?>">
                <?php
                foreach($url as $res => $u) {
                    if (!empty($u)) {
                        echo '<li role="menuitemradio" aria-checked="' . ($res == $defaultRes ? 'true' : 'false') . '" tabindex="0" class="option_' . $videoObjectIdentifier . '" id="option_' . $videoObjectIdentifier . '-' . $res . '" data-url="' . $u . '">' . ($res == $defaultRes ? '<i class="material-icons" aria-hidden="true">done</i>' : '') . $res . 'p</li>';
                    } else {
                        echo '<li role="menuitemradio" disabled="true" aria-disabled="true" aria-checked="false" class="edusharing_rendering_content_video_options_resolutions_converting" title="' . $conversionMsg->localize($Locale, $Translate) . '">' . $res . 'p</li>';
                    }
                }
                ?>
            </ul>
        </div>
    </div>
    <?php if (isset($footer)){
        echo $footer;
    } ?>
    <p id="e_<?php echo $videoObjectIdentifier ?>" class="edusharing_rendering_content_video_error"><?php echo $errMsg->localize($Locale, $Translate); ?></p>
    <?php
    echo '<data class="edu_video_data" value="' . htmlspecialchars(json_encode([
        'id'          => $videoObjectIdentifier,
        'resolutions' => array_values($videoResolutions),
    ]), ENT_QUOTES, 'UTF-8') . '"></data>';
    ?>
</div>