<?php
    global $Locale, $Translate;
    $msg = array();
    $msg['back'] = new Phools_Message_Default('back');
    if(!empty($backLink))
        $backCloseHref = $backLink;
    else 
        $backCloseHref = 'javascript:window.close();';
?>
<html>
 <head>
         <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <title><?php echo htmlentities($title) ?></title>
    <link rel="stylesheet" type="text/css" href="../../theme/default/css/display.css">
     <link rel="stylesheet" type="text/css" href="../../theme/default/module/doc/odf/css/webodf.css">
     <link rel="stylesheet" type="text/css" href="../../theme/default/module/doc/odf/css/custom.css">
  <script src="../../theme/default/module/doc/odf/js/webodf.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript" charset="utf-8">
    function init() {
        var odfelement = document.getElementById("odf"), odfcanvas = new odf.OdfCanvas(odfelement);
        odfcanvas.load("<?php echo $path ?>");
    }
    window.setTimeout(init, 0);
  </script>
 </head>
 <body>
   <header class="no-print">
            <nav>
                <a class="action left" href="<?php echo $backCloseHref; ?>">&#9668;&nbsp;<?php echo $msg['back'] -> localize($Locale, $Translate); ?></a>
             </nav>
             <span class="caption"><?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?></span>
        </header>
        <section>
          <div id="odf"></div>
          <br/>
          <?php echo $license ?>
        </section>
 </body>
</html>





