<?php 
global $Locale, $Translate;
$msg = array();
$msg['ltiGotoProvider'] = new Phools_Message_Default('ltiGotoProvider');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
<?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo $title ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
        <?php echo $applyDataProtectionRegulationsDialog?>
		<iframe id="lti_frame_<?php echo $objectId?>" name="lti_frame_<?php echo $objectId?>" src="" style="<?php($applyDataProtectionRegulationsDialog?'display:none':'')?>border: none; width: 80%; min-height: 600px;margin: auto;"></iframe>
       <br/><a href="#" id="edusharing_rendering_content_href" class="edusharing_rendering_content"><?php echo $msg['ltiGotoProvider']->localize($Locale, $Translate)?></a>
</div>
	<?php echo $metadata; ?>
</div>

<?php echo $launchForm?>

<script>
   document.getElementById("edusharing_rendering_content_href").onclick = function() {document.getElementById('ltiLaunchForm_<?php echo $objectId?>').submit(); return false; }
</script>

<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>