<?php
global $Locale, $Translate;
$msg = array();
$msg['hasNoContentLicense'] = new Phools_Message_Default('hasNoContentLicense');
?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<div>

    <?php
    if(false === Config::get('renderInfoLMSReturn')->hasContentLicense) {
        echo '<span class="edusharing_warning">'.htmlentities($msg['hasNoContentLicense']->localize($Locale, $Translate), ENT_COMPAT, 'utf-8').'</span>';
    } else {
        echo '<div style="display:none">' . $launchForm . '</div>'.
            '<a href="#" onclick="document.getElementById(\'ltiLaunchForm_'.$objectId.'\').target=\'_blank\';document.getElementById(\'ltiLaunchForm_'.$objectId.'\').submit(); return false;" target="_blank">LTI: <es:title xmlns:es="http://edu-sharing.net/object">'.$title.'</es:title></a>';
    }
    ?>
    <?php $footer?>
</div>