<?php $licid = uniqid();?>

<iframe name="lti_frame_<?php echo $objectId?>" src="" style="border: none; width: 80%; min-height: 400px;"></iframe>
<?php echo $launchForm?>


<?php echo (!empty($license)? $license : '<p class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</p>')?>
<?php echo $metadata?>
<script>
    var obj_<?php echo $licid;?> = document.querySelector("[data-licid='<?php echo $licid;?>']");
    obj_<?php echo $licid;?>.onload = function() {
	    var wrapper_<?php echo $licid;?> = obj_<?php echo $licid;?>.parentNode;
	    if((' ' + wrapper_<?php echo $licid?>.className + ' ').indexOf(' edu_wrapper ') > -1) {
		    var objWidth_<?php echo $licid;?> = obj_<?php echo $licid;?>.clientWidth + 'px';
		    for (var i = 0; i < wrapper_<?php echo $licid;?>.childNodes.length; i++) {
		    	if (wrapper_<?php echo $licid;?>.childNodes[i].className == "license") {
		        	wrapper_<?php echo $licid;?>.childNodes[i].style.width = objWidth_<?php echo $licid;?>;
		    		wrapper_<?php echo $licid;?>.style.height = 'auto';
		    		obj_<?php echo $licid;?>.style.height = 'auto';
		          	break;
		        }
		    }
	    }
    }
</script>