<?php
global $Locale, $Translate, $MC_URL;
$msg = array();
$msg['goToOrigin'] = new Phools_Message_Default('goToOrigin');
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>

<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
    <div class="edusharing_rendering_content_wrapper" >
        <iframe title="<?php echo htmlentities($title) ?>" id="<?php echo $uniqueId?>" src="<?php echo $url?>" width="95%" height="100%" style="border: none; height: 80vh" ></iframe>
    </div>
</div>

<?php echo $metadata; ?>
</div>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script>
    $('#edusharing_toggle_fullscreen').on('click', function(){
        // if already full screen; exit
        // else go fullscreen
        if (
            document.fullscreenElement ||
            document.webkitFullscreenElement ||
            document.mozFullScreenElement ||
            document.msFullscreenElement
        ) {
            if (document.exitFullscreen) {
                document.exitFullscreen();
            } else if (document.mozCancelFullScreen) {
                document.mozCancelFullScreen();
            } else if (document.webkitExitFullscreen) {
                document.webkitExitFullscreen();
            } else if (document.msExitFullscreen) {
                document.msExitFullscreen();
            }
        } else {
            element = $('.edusharing_rendering_fullscreen_wrapper').get(0);
            if (element.requestFullscreen) {
                element.requestFullscreen();
            } else if (element.mozRequestFullScreen) {
                element.mozRequestFullScreen();
            } else if (element.webkitRequestFullscreen) {
                element.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
            } else if (element.msRequestFullscreen) {
                element.msRequestFullscreen();
            }
        }
    });
</script>
