<?php 
global $Locale, $Translate;
$licid = $uniqueId . '_lic';
$msg['showInLearningAppsOrg'] = new Phools_Message_Default('showInLearningAppsOrg');
?>

<div>
    <style>
        <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
        <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
    </style>
    <?php echo $dataProtectionRegulationsDialog; ?>
    <iframe id="<?php echo $uniqueId?>" src="<?php echo $url?>" data-licid="<?php echo $licid;?>" width="100%" height="500px" style="border: none;<?php echo empty($dataProtectionRegulationsDialog) ? '' : 'display:none;' ?>" ></iframe>
    <br/><a href="<?php echo $originUrl?>" target="_blank" title="<?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?>"><?php echo htmlentities($msg['showInLearningAppsOrg']->localize($Locale, $Translate)) ?></a>
    <?php echo $footer?>
</div>
