<div id="edusharing_rendering_content">
Öffnen des Objekts nicht möglich, leider.<br/><br/>
Um das Objekt trotdzem zu ... herunterladen.<br/><br/><br/>
Vorschaubild:<br/>
<pre>
----------------------
| Muss über API oder |
| mit Signatur       |
| abgeholt werden.   |
----------------------
</pre>

<a href="<?php echo $url ?>" target="_blank"  >[DOWNLOAD]</es:title></a>
</div>
<span id="edusharing_rendering_metadata_toggle">TOGGLE</span>
<div id="edusharing_rendering_metadata">
<h1>Titel des Objekts</h1>
<label>Eigentümer</label>
<span>Name des Eigentümers</span>
<label>Quelle</label>
<span>Name der Quelle</span>
<label>Lizenz</label>
<span>Bild und Text der Lizenz</span>
<label>Weitere Metadaten</label>
<span>kommen hier</span>
</div>