<?php 
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
?>

<style scoped>
<?php include(dirname(__FILE__) . '/../../css/dynamic.css'); ?>
</style>

<div class="edusharing_rendering_wrapper">
	<div class="edusharing_rendering_metadata_top"><span id="edusharing_rendering_metadata_top_toggle" class="edusharing_rendering_cursor_pointer" onClick="toggle_edusharing_rendering_metadata()"><?php echo $msg['hideInformation']->localize($Locale, $Translate);?></span></div>
		<?php echo $metadata?>
	<div class="edusharing_rendering_content_wrapper">
		<h1>Öffnen des Objekts leider nicht möglich.</h1>
		Um das Objekt trotzdem zu benutzen, können Sie es herunterladen.<br/><br/>
		<a href="<?php echo $url ?>" target="_blank" class="edusharing_rendering_content" >Download</a>
	</div>
</div>

<script>
	<?php include(dirname(__FILE__) . '/../../js/dynamic.js'); ?>
</script>


