<?php
global $Locale, $Translate;
$msg = array();
$msg['hasNoContentLicense'] = new Phools_Message_Default('hasNoContentLicense');
?>
<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.php'); ?>
</style>
<div class="edusharing_rendering_content_wrapper" style="display: inline-block">
<?php echo $footer?>
</div>
