<?php
global $Locale, $Translate;
$msg = array();
$msg['hasNoContentLicense'] = new Phools_Message_Default('hasNoContentLicense');
?>

<style scoped>
    <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/inline.css'); ?>
</style>
<span>


    <?php
    if(false === Config::get('hasContentLicense')) {
        echo '<span class="warning">'.$msg['hasNoContentLicense']->localize($Locale, $Translate).'</span>';
    } else {
        echo '<a href="'. htmlentities($url, ENT_COMPAT, 'utf-8').'" target="_blank"  ><es:title xmlns:es="http://edu-sharing.net/object" >'.$title.'</es:title></a>';
    }
    ?>
<?php if(!empty($metadata) || !empty($license)) {
	echo '&nbsp;(<span style="display: inline-block">'.$license.'</span>';
	if(!empty($metadata) && !empty($license))
		echo '&nbsp|&nbsp';
	echo '<span style="display: inline-block">'.$metadata.'</span>)';
}?>
</span>
