<span>
<a href="<?php echo htmlentities($url, ENT_COMPAT, 'utf-8') ?>" target="_blank"  ><es:title xmlns:es="http://edu-sharing.net/object" ><?php echo $title;?></es:title></a>
<?php if(!empty($metadata) || !empty($license)) {
	echo '&nbsp;(<span style="display: inline-block">'.$license.'</span>';
	if(!empty($metadata) && !empty($license))
		echo '&nbsp|&nbsp';
	echo '<span style="display: inline-block">'.$metadata.'</span>)';
}?>
</span>
