<?php
global $Locale, $Translate;
$msg = array();
$msg['showInformation'] = new Phools_Message_Default('showInformation');
$msg['hideInformation'] = new Phools_Message_Default('hideInformation');
$msg['goToCourse'] = new Phools_Message_Default('goToCourse');
?>

    <style>
        <?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
        <?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
    </style>

    <div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
        <h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
        <div class="edusharing_rendering_content_wrapper" >
            <div>
                <iframe src="<?php echo $url ?>" width="800" height="500" style="border:none;"></iframe>
            </div>
            <a href="<?php echo $url2 ?>" target="_blank" class="edusharing_rendering_content" id="edusharing_rendering_content_href"><?php echo $msg['goToCourse']->localize($Locale, $Translate);?></a>
        </div>
        <?php echo $metadata; ?>
    </div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>
