<?php
    global $Locale, $Translate;
    $msg = array();
    $msg['back'] = new Phools_Message_Default('back');

?>
<html>
    <head>
        <title>edu-sharing edunex module</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="../../theme/default/css/display.css">
        <link rel="stylesheet" type="text/css" href="../../theme/default/css/custom.css">
        <link rel="stylesheet" type="text/css" href="../../theme/default/plugin/edunex/css/style.css">
        <script>var single=1; </script>
    </head>
    <body>
        <header class="no-print">
            <nav>
                <a class="action left" href="javascript:history.back();window.close();">&#9668;&nbsp;<?php echo $msg['back']->localize($Locale, $Translate);?></a>
                <span class="caption"><?php echo htmlentities($title, ENT_QUOTES, 'UTF-8') ?></span>
            </nav>
        </header>
        <section>
            <?php echo $edunexStuff ?>
        </section>
    </body>
</html>
