<?php 
global $Locale, $Translate;
$msg = array();
$msg['imageDescriptionNotAvailable'] = new Phools_Message_Default('imageDescriptionNotAvailable');
?>

<style>
    <?php include(dirname(__FILE__) . '/../../css/embed.css'); ?>
    <?php include(dirname(__FILE__) . '/../../css/material-icons.php'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
    <div class="edusharing_rendering_content_wrapper" >
        <img
            class="edusharing_rendering_content"
            src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>"
			alt="<?php echo $msg['imageDescriptionNotAvailable'] -> localize($Locale, $Translate) ?>"
        >
    </div>
    <?php echo $footer?>
</div>
