<div class="edusharing_rendering_content_footer">
  <div class="edusharing_rendering_content_footer_top">
      <?php echo (!empty($license)? htmlspecialchars_decode($license,  ENT_QUOTES ) : '<a target="_blank" href="'.$url.'" class="edu_sharing_filename">' . htmlentities($title, ENT_QUOTES, 'UTF-8') . '</a>'); ?>
      <?php echo $metadata ?>
  </div>
  <div class="edusharing_rendering_content_footer_bot">
      <?php echo $sequence;?>
  </div>
</div>
