<div class="license" style="max-width: 100%">
<?php

global $Locale, $Translate;
$msg = array();
$msg['customLicense'] = new Phools_Message_Default('custom license');

$licenceContent = '<a class="license_permalink" href="'.$license_permalink.'" target="_blank" title="'.htmlentities($license_filename).'"><es:title xmlns:es="http://edu-sharing.net/object" >'
                    . htmlentities($license_filename)
                    . '</es:title></a>'
                    . '&nbsp;';
if(!empty($license_author)) {
    $licenceContent .= '<br/>' . htmlentities($this->translate('authored_by'), ENT_COMPAT, 'utf-8')
                    . '&nbsp;'
                    . '<span class="author">'
                    . htmlentities($license_author, ENT_QUOTES, 'utf-8') . '</span>'
                    . '&nbsp;';
}
$licenceContent .=  htmlentities($this->translate('published under a'), ENT_COMPAT, 'utf-8')
                    . '&nbsp;';
                    if(!empty($license_icon_url)) {
                        $licenceContent .= '<a target="_blank" class="license_link" href="' . htmlspecialchars($license_url, ENT_QUOTES, 'utf-8') . '">';
                        $licenceContent .= '<img class="license_icon" style="height: 16px" src="' . htmlspecialchars($license_icon_url, ENT_QUOTES, 'utf-8') . '" />';
                        $licenceContent .= '</a>';    
                    } else { 
                        $licenceContent .= $msg['customLicense']->localize($Locale, $Translate);
                    }
                    
                    
echo $licenceContent;
?>
</div>