<div class="license" style="max-width: 100%">
<?php

global $Locale, $Translate;
$msg = array();
$msg['customLicense'] = new Phools_Message_Default('custom license');

$licenceContent =  Config::get('licensePre', '');

$licenceContent .= '<a class="license_permalink" href="'.$license_permalink.'" target="_blank" title="'.$license_filename.'"><es:title xmlns:es="http://edu-sharing.net/object" >'
                    . htmlentities($license_filename)
                    . '</es:title></a>'
                    . '&nbsp;';
if(!empty($license_author)) {
    $licenceContent .= '<br/>' . $this->translate('authored_by')
                    . '&nbsp;'
                    . '<span class="author">'
                    . $license_author. '</span>'
                    . '&nbsp;';
}
$licenceContent .=  htmlentities($this->translate('published under a'), ENT_COMPAT, 'utf-8')
                    . '&nbsp;';
                    if(!empty($license_icon_url)) {
                        $licenceContent .= '<a target="_blank" class="license_link" href="' . $license_url . '">';
                        $licenceContent .= '<img class="license_icon" style="height: 16px" src="' . $license_icon_url . '" />';
                        $licenceContent .= '</a>';    
                    } else { 
                        $licenceContent .= $msg['customLicense']->localize($Locale, $Translate);
                    }

$licenceContent .= Config::get('licensePost', '');

echo utf8_encode($licenceContent);
?>
</div>