<?php 
global $Locale, $Translate, $MC_URL;
$msg = array();
$msg['imageDescriptionNotAvailable'] = new Phools_Message_Default('imageDescriptionNotAvailable');
?>

<style>
<?php include(dirname(__FILE__) . '/../../css/dynamic.php'); ?>
<?php include(dirname(__FILE__) . '/../../css/metadata.css'); ?>
</style>
<div class="edusharing_rendering_wrapper" vocab="http://schema.org/" typeof="WebPage">
	<h1 class="edusharing_rendering_content_title"><?php echo htmlentities($title) ?></h1>
	<div class="edusharing_rendering_content_wrapper" role="main">
        <div class="edusharing_rendering_fullscreen_wrapper">
            <img
                    class="edusharing_rendering_content"
                    src="<?php echo htmlentities($image_url, ENT_QUOTES, 'UTF-8') ?>"
                    alt="<?php echo $msg['imageDescriptionNotAvailable'] -> localize($Locale, $Translate) ?>"
            >
            <i id="edusharing_toggle_fullscreen" class="material-icons">fullscreen</i>
        </div>
	</div>
	<?php echo $metadata; ?>
</div>
<?php
$downloadUrl = Config::get('downloadUrl');
if(!empty($downloadUrl))
    echo '<script>try{window.ngRender.setDownloadUrl("'.$downloadUrl.'");}catch(err){}</script>';
?>

<script src="<?php echo $MC_URL?>/vendor/js/getJS.php"></script>
<script>
    $('#edusharing_toggle_fullscreen').on('click', function(){
        // if already full screen; exit
        // else go fullscreen
        if (
            document.fullscreenElement ||
            document.webkitFullscreenElement ||
            document.mozFullScreenElement ||
            document.msFullscreenElement
        ) {
            if (document.exitFullscreen) {
                document.exitFullscreen();
            } else if (document.mozCancelFullScreen) {
                document.mozCancelFullScreen();
            } else if (document.webkitExitFullscreen) {
                document.webkitExitFullscreen();
            } else if (document.msExitFullscreen) {
                document.msExitFullscreen();
            }
        } else {
            element = $('.edusharing_rendering_fullscreen_wrapper').get(0);
            if (element.requestFullscreen) {
                element.requestFullscreen();
            } else if (element.mozRequestFullScreen) {
                element.mozRequestFullScreen();
            } else if (element.webkitRequestFullscreen) {
                element.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
            } else if (element.msRequestFullscreen) {
                element.msRequestFullscreen();
            }
        }
    });
</script>
