########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

    pdb:
      enabled: false

    storage:

      data:
        permission: false
        spec: {}

    sysctl:
      enabled: false

  image:
    pullPolicy: Always
    pullSecrets: []
    registry: ${docker.registry}
    repository: ${docker.repository}

  metrics:
    scrape:
      interval: 10s
      timeout: 10s
    servicemonitor:
      enabled: false

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-rediscluster

image:
  prefix: ${docker.prefix}
  tag: ${docker.tag}

########################################################################################################################

service:

  port:
    api: 6379
    gossip: 16379
    metrics: 9114

########################################################################################################################

config:

  aof:
    enabled: true

  cluster:
    master: 3
    replicas: 1
    wait: 30

  extra: {}
#   save: ""

########################################################################################################################

nodeAffinity: {}
podAntiAffinity: "soft"

tolerations: []

########################################################################################################################

persistence:

  data:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

########################################################################################################################

podAnnotations: {}

podSecurityContext:

  runAsUser: 1001
  fsGroup: 1001
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

########################################################################################################################

terminationGracePeriod: 120

startupProbe:

  failureThreshold: 30
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    cpu: 250m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 1Gi

########################################################################################################################

init:

  permission:

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      runAsUser: 0

  sysctl:

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      privileged: true
      runAsUser: 0

########################################################################################################################

sidecar:

  metrics:

    enabled: true

    resources:

      limits:
        cpu: 125m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 512Mi

    securityContext:

      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

########################################################################################################################
